[2022-11-29T03:57:10.320+0000] {processor.py:154} INFO - Started process (PID=45) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T03:57:10.336+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T03:57:10.351+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:10.351+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T03:57:15.349+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:15.348+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-toosvh62 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T03:57:16.109+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:16.107+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T03:57:17.311+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T03:57:17.789+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:17.787+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T03:57:17.895+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:17.894+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-28T00:00:00+00:00, run_after=2022-11-29T00:00:00+00:00
[2022-11-29T03:57:17.973+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 7.681 seconds
[2022-11-29T03:57:48.952+0000] {processor.py:154} INFO - Started process (PID=82) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T03:57:48.957+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T03:57:48.968+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:48.968+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T03:57:55.908+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:55.908+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-3d4r3plu because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T03:57:56.089+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:56.089+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T03:57:56.488+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T03:57:56.563+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:56.562+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T03:57:56.595+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:56.595+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T03:57:56.608+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 7.682 seconds
[2022-11-29T03:58:28.660+0000] {processor.py:154} INFO - Started process (PID=111) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T03:58:28.687+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T03:58:28.689+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:58:28.689+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T03:58:53.612+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:58:53.612+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-p62y77kz because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T03:58:53.798+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:58:53.798+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T03:58:54.105+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T03:58:54.158+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:58:54.157+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T03:58:54.183+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:58:54.183+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T03:58:54.206+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 25.623 seconds
[2022-11-29T03:59:26.230+0000] {processor.py:154} INFO - Started process (PID=144) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T03:59:26.375+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T03:59:27.512+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:59:27.483+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T03:59:59.423+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:59:57.988+0000] {timeout.py:68} ERROR - Process timed out, PID: 144
[2022-11-29T04:00:00.856+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:59:59.522+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 122, in <module>
    from pandas.core.describe import describe_ndframe
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/describe.py", line 39, in <module>
    from pandas.io.formats.format import format_percentiles
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 99, in <module>
    from pandas.io.common import stringify_path
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 59, in <module>
    @dataclasses.dataclass
  File "/usr/local/lib/python3.7/dataclasses.py", line 1010, in dataclass
    return wrap(_cls)
  File "/usr/local/lib/python3.7/dataclasses.py", line 1002, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/local/lib/python3.7/dataclasses.py", line 921, in _process_class
    globals,
  File "/usr/local/lib/python3.7/dataclasses.py", line 523, in _init_fn
    return_type=None)
  File "/usr/local/lib/python3.7/dataclasses.py", line 387, in _create_fn
    exec(txt, globals, ns)
  File "<string>", line 1, in <module>
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 144
[2022-11-29T04:00:01.532+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:00:03.188+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 37.110 seconds
[2022-11-29T04:00:42.820+0000] {processor.py:154} INFO - Started process (PID=176) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:00:43.401+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:00:44.443+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:00:44.122+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:01:15.483+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:01:15.074+0000] {timeout.py:68} ERROR - Process timed out, PID: 176
[2022-11-29T04:01:16.984+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:01:15.799+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 7, in <module>
    from pandas.core.util.hashing import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/util/hashing.py", line 18, in <module>
    from pandas._libs.hashing import hash_object_array
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 176
[2022-11-29T04:01:18.061+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:01:48.676+0000] {processor.py:154} INFO - Started process (PID=204) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:01:48.839+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:01:49.054+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:01:48.981+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:02:20.188+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:02:20.077+0000] {timeout.py:68} ERROR - Process timed out, PID: 204
[2022-11-29T04:02:40.729+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:02:21.387+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 21, in init pandas._libs.tslibs.offsets
  File "<frozen importlib._bootstrap>", line 978, in _find_and_load
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 204
[2022-11-29T04:02:42.158+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:02:58.130+0000] {processor.py:154} INFO - Started process (PID=224) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:02:58.168+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:02:58.834+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:02:58.530+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:03:36.784+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:03:36.744+0000] {timeout.py:68} ERROR - Process timed out, PID: 224
[2022-11-29T04:03:38.772+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:03:37.884+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/tzconversion.pyx", line 1, in init pandas._libs.tslibs.tzconversion
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 224
[2022-11-29T04:03:39.760+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:04:45.614+0000] {processor.py:154} INFO - Started process (PID=241) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:04:45.874+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:04:46.030+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:04:45.995+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:05:19.694+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:05:16.754+0000] {timeout.py:68} ERROR - Process timed out, PID: 241
[2022-11-29T04:05:25.103+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:05:22.175+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1396, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1352, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1029, in __init__
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 241
[2022-11-29T04:05:26.419+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:06:43.631+0000] {processor.py:154} INFO - Started process (PID=245) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:06:44.964+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:06:45.160+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:06:45.097+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:07:16.395+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:07:15.859+0000] {timeout.py:68} ERROR - Process timed out, PID: 245
[2022-11-29T04:07:18.042+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:07:17.111+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timestamps.pyx", line 1956, in init pandas._libs.tslibs.timestamps
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/core/getlimits.py", line 514, in __init__
    def __init__(self, int_type):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 245
[2022-11-29T04:07:18.551+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:08:02.318+0000] {processor.py:154} INFO - Started process (PID=248) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:08:02.803+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:08:03.430+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:08:03.359+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:08:36.114+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:08:35.783+0000] {timeout.py:68} ERROR - Process timed out, PID: 248
[2022-11-29T04:08:36.722+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:08:36.266+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 6, in <module>
    import pyarrow as pa
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 248
[2022-11-29T04:08:37.731+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:09:28.986+0000] {processor.py:154} INFO - Started process (PID=253) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:09:33.471+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:09:34.865+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:09:34.757+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:10:20.550+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:10:20.134+0000] {timeout.py:68} ERROR - Process timed out, PID: 253
[2022-11-29T04:12:46.150+0000] {processor.py:154} INFO - Started process (PID=256) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:12:47.016+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:12:47.425+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:12:47.407+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:13:22.511+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:13:22.149+0000] {timeout.py:68} ERROR - Process timed out, PID: 256
[2022-11-29T04:13:35.748+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:13:23.001+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 256
[2022-11-29T04:13:38.365+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:14:16.670+0000] {processor.py:154} INFO - Started process (PID=259) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:14:17.576+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:14:18.487+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:14:18.328+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:14:50.759+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:14:50.568+0000] {timeout.py:68} ERROR - Process timed out, PID: 259
[2022-11-29T04:14:52.985+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:14:50.903+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 259
[2022-11-29T04:15:33.775+0000] {processor.py:154} INFO - Started process (PID=262) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:15:34.522+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:15:35.269+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:15:35.063+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:16:09.626+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:16:08.599+0000] {timeout.py:68} ERROR - Process timed out, PID: 262
[2022-11-29T04:16:23.192+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:16:10.824+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 7, in <module>
    from pandas.core.util.hashing import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/util/hashing.py", line 17, in <module>
    from pandas._libs import lib
  File "pandas/_libs/lib.pyx", line 1, in init pandas._libs.lib
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 262
[2022-11-29T04:17:27.548+0000] {processor.py:154} INFO - Started process (PID=265) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:17:30.577+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:17:31.616+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:17:31.175+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:18:30.073+0000] {processor.py:154} INFO - Started process (PID=267) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:18:32.682+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:18:33.345+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:18:33.052+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:19:05.683+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:19:05.054+0000] {timeout.py:68} ERROR - Process timed out, PID: 267
[2022-11-29T04:19:06.746+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:19:06.260+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 35, in init pandas._libs.tslibs.offsets
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 267
[2022-11-29T04:19:07.909+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:39:15.281+0000] {processor.py:154} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:39:15.293+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:39:15.304+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:15.303+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:39:19.864+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:19.863+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-v4b8vef1 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T04:39:20.333+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:20.330+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T04:39:21.477+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:39:21.705+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:21.704+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T04:39:21.758+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:21.757+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T04:39:21.826+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 6.607 seconds
[2022-11-29T04:39:52.950+0000] {processor.py:154} INFO - Started process (PID=71) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:39:52.954+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:39:52.957+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:52.956+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:39:55.779+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:55.778+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-1u6ahv3x because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T04:39:56.005+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:56.005+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T04:39:56.457+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:39:56.518+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:56.518+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T04:39:56.557+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:56.557+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T04:39:56.575+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 3.638 seconds
[2022-11-29T04:40:28.597+0000] {processor.py:154} INFO - Started process (PID=98) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:40:28.649+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:40:28.662+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:40:28.662+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:40:58.909+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:40:58.789+0000] {timeout.py:68} ERROR - Process timed out, PID: 98
[2022-11-29T04:41:34.650+0000] {processor.py:154} INFO - Started process (PID=136) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:41:34.734+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:41:34.762+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:41:34.759+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:42:34.605+0000] {processor.py:154} INFO - Started process (PID=167) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:42:34.675+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:42:34.678+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:42:34.678+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:43:05.924+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:43:05.828+0000] {timeout.py:68} ERROR - Process timed out, PID: 167
[2022-11-29T04:43:06.249+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:43:05.972+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 20, in <module>
    from pandas.core.arrays.string_arrow import ArrowStringArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/string_arrow.py", line 65, in <module>
    import pyarrow.compute as pc
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 18, in <module>
    from pyarrow._compute import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 167
[2022-11-29T04:43:06.352+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:43:08.455+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 33.732 seconds
[2022-11-29T04:43:41.515+0000] {processor.py:154} INFO - Started process (PID=199) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:43:41.532+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:43:41.558+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:43:41.555+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:44:11.688+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:44:11.653+0000] {timeout.py:68} ERROR - Process timed out, PID: 199
[2022-11-29T04:44:11.737+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:44:11.693+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 143, in <module>
    from pandas.io.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/api.py", line 8, in <module>
    from pandas.io.excel import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/__init__.py", line 6, in <module>
    from pandas.io.excel._odswriter import ODSWriter as _ODSWriter
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_odswriter.py", line 15, in <module>
    from pandas.io.formats.excel import ExcelCell
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 199
[2022-11-29T04:44:11.748+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:44:12.074+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 30.625 seconds
[2022-11-29T04:44:44.103+0000] {processor.py:154} INFO - Started process (PID=232) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:44:44.216+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:44:45.722+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:44:44.493+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:45:19.005+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:45:18.737+0000] {timeout.py:68} ERROR - Process timed out, PID: 232
[2022-11-29T04:45:19.645+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:45:19.126+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 29, in <module>
    from pandas._libs import (
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 232
[2022-11-29T04:45:19.953+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:45:20.982+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 36.913 seconds
[2022-11-29T04:45:54.872+0000] {processor.py:154} INFO - Started process (PID=264) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:45:54.939+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:45:54.990+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:45:54.984+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:48:02.488+0000] {processor.py:154} INFO - Started process (PID=297) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:48:02.519+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:48:02.767+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:48:02.713+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:48:33.181+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:48:32.824+0000] {timeout.py:68} ERROR - Process timed out, PID: 297
[2022-11-29T04:48:33.500+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:48:33.278+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 7, in <module>
    from pandas.core.arrays.categorical import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 99, in <module>
    from pandas.core.base import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 297
[2022-11-29T04:48:33.976+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:48:36.612+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 34.624 seconds
[2022-11-29T04:49:09.810+0000] {processor.py:154} INFO - Started process (PID=335) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:49:09.852+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:49:09.948+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:49:09.933+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:49:56.872+0000] {processor.py:154} INFO - Started process (PID=362) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:49:56.889+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:49:56.903+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:49:56.896+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:50:53.833+0000] {processor.py:154} INFO - Started process (PID=396) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:50:53.854+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:50:53.872+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:50:53.869+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:51:30.175+0000] {processor.py:154} INFO - Started process (PID=418) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:51:30.197+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:51:30.199+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:51:30.199+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:52:10.633+0000] {processor.py:154} INFO - Started process (PID=442) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:52:10.642+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:52:10.650+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:52:10.650+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:52:51.252+0000] {processor.py:154} INFO - Started process (PID=457) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:52:51.259+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:52:51.269+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:52:51.269+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:53:52.773+0000] {processor.py:154} INFO - Started process (PID=486) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:53:52.782+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T04:53:52.844+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:53:52.842+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T04:54:25.012+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:54:23.762+0000] {timeout.py:68} ERROR - Process timed out, PID: 486
[2022-11-29T04:54:27.605+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:54:25.854+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 144, in <module>
    from pandas.core.window import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (  # noqa:F401
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/window/ewm.py", line 11, in <module>
    import pandas._libs.window.aggregations as window_aggregations
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 486
[2022-11-29T04:54:31.401+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:06:38.722+0000] {processor.py:154} INFO - Started process (PID=53) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:06:38.738+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T05:06:38.748+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:06:38.748+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:07:41.613+0000] {processor.py:154} INFO - Started process (PID=93) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:07:41.618+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T05:07:41.626+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:07:41.625+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:07:48.062+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:07:48.061+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-nf4nx7fj because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T05:07:48.365+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:07:48.364+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T05:07:49.607+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:07:49.927+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:07:49.926+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T05:07:50.060+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:07:50.060+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T05:07:50.193+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 8.632 seconds
[2022-11-29T05:08:55.424+0000] {processor.py:154} INFO - Started process (PID=140) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:08:55.433+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T05:08:55.451+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:08:55.450+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:09:04.465+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:09:04.463+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-79_en9s1 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T05:09:05.518+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:09:05.507+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T05:09:06.844+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:09:07.179+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:09:07.177+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T05:09:07.515+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:09:07.510+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T05:09:07.589+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 12.262 seconds
[2022-11-29T05:09:40.146+0000] {processor.py:154} INFO - Started process (PID=176) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:09:40.167+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T05:09:40.175+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:09:40.175+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:10:10.581+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:10:10.319+0000] {timeout.py:68} ERROR - Process timed out, PID: 176
[2022-11-29T05:10:10.829+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:10:10.635+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 143, in <module>
    from pandas.io.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/api.py", line 32, in <module>
    from pandas.io.sas import read_sas
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 176
[2022-11-29T05:10:10.923+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:10:16.165+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 36.061 seconds
[2022-11-29T05:11:00.859+0000] {processor.py:154} INFO - Started process (PID=218) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:11:00.902+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T05:11:00.916+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:11:00.915+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:11:31.722+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:11:31.327+0000] {timeout.py:68} ERROR - Process timed out, PID: 218
[2022-11-29T05:11:31.899+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:11:31.784+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 8, in <module>
    from pandas.core.arrays.datetimes import DatetimeArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 67, in <module>
    from pandas.core.arrays import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimelike.py", line 121, in <module>
    from pandas.tseries import frequencies
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 218
[2022-11-29T05:11:32.037+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:11:33.195+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 33.613 seconds
[2022-11-29T05:12:33.891+0000] {processor.py:154} INFO - Started process (PID=257) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:12:35.287+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T05:12:36.631+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:12:36.481+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:13:11.441+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:13:09.070+0000] {timeout.py:68} ERROR - Process timed out, PID: 257
[2022-11-29T05:13:15.777+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:13:12.963+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 9, in <module>
    _palv = Version(_pa_version)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/version/__init__.py", line 362, in __init__
    self._version.local,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/version/__init__.py", line 534, in _cmpkey
    reversed(list(itertools.dropwhile(lambda x: x == 0, reversed(release))))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 257
[2022-11-29T05:13:16.561+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:14:16.464+0000] {processor.py:154} INFO - Started process (PID=287) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:14:23.069+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T05:14:36.912+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:14:34.945+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:15:15.031+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:15:11.996+0000] {timeout.py:68} ERROR - Process timed out, PID: 287
[2022-11-29T05:15:22.338+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:15:16.687+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 432, in __new__
    partial_desc = vars(new_cls)["partial"]
KeyError: 'partial'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 2, in <module>
    from airflow.operators.python import PythonOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 196, in <module>
    class BranchPythonOperator(PythonOperator, SkipMixin):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 434, in __new__
    partial_desc.class_method = classmethod(partial)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 287
[2022-11-29T05:15:23.770+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:17:55.107+0000] {processor.py:154} INFO - Started process (PID=344) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:17:56.658+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T05:17:57.927+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:17:57.897+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:18:32.611+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:18:32.522+0000] {timeout.py:68} ERROR - Process timed out, PID: 344
[2022-11-29T05:22:31.335+0000] {processor.py:154} INFO - Started process (PID=383) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:22:35.352+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T05:22:43.141+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:22:42.310+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:23:22.974+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:23:18.591+0000] {timeout.py:68} ERROR - Process timed out, PID: 383
[2022-11-29T05:23:40.295+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:23:25.854+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 2, in <module>
    from airflow.operators.python import PythonOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 83, in <module>
    class PythonOperator(BaseOperator):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 435, in __new__
    new_cls.__init__ = cls._apply_defaults(new_cls.__init__)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 328, in _apply_defaults
    sig_cache = signature(func)
  File "/usr/local/lib/python3.7/inspect.py", line 3083, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/local/lib/python3.7/inspect.py", line 2833, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/usr/local/lib/python3.7/inspect.py", line 2284, in _signature_from_callable
    return _signature_from_function(sigcls, obj)
  File "/usr/local/lib/python3.7/inspect.py", line 2154, in _signature_from_function
    kind=_POSITIONAL_OR_KEYWORD))
  File "/usr/local/lib/python3.7/inspect.py", line 2469, in __init__
    self._kind = _ParameterKind(kind)
  File "/usr/local/lib/python3.7/enum.py", line 315, in __call__
    return cls.__new__(cls, value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 383
[2022-11-29T05:23:46.584+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:25:04.375+0000] {processor.py:154} INFO - Started process (PID=432) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:25:05.791+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T05:25:06.756+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:25:06.352+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:25:42.125+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:25:40.137+0000] {timeout.py:68} ERROR - Process timed out, PID: 432
[2022-11-29T05:27:43.442+0000] {processor.py:154} INFO - Started process (PID=503) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T05:27:46.909+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T05:27:49.853+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:27:49.508+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:01:13.294+0000] {processor.py:154} INFO - Started process (PID=34) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:01:13.297+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:01:13.300+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:01:13.299+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:01:22.015+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:01:22.014+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-8r6d11vx because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T07:01:23.597+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:01:23.595+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T07:01:27.180+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:02:08.645+0000] {processor.py:154} INFO - Started process (PID=71) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:02:08.987+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:02:09.720+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:02:09.666+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:02:16.378+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:02:16.377+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-pwz_y0nf because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T07:02:16.616+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:02:16.615+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T07:02:16.978+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:02:17.086+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:02:17.086+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T07:02:17.116+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:02:17.116+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T07:02:17.144+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 9.633 seconds
[2022-11-29T07:02:48.562+0000] {processor.py:154} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:02:48.578+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:02:48.594+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:02:48.593+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:03:07.751+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:07.751+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-4gx8y8of because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T07:03:07.945+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:07.944+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T07:03:08.321+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:03:08.383+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:08.383+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T07:03:08.422+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:08.422+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T07:03:08.438+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 19.912 seconds
[2022-11-29T07:03:40.188+0000] {processor.py:154} INFO - Started process (PID=145) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:03:40.198+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:03:40.204+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:40.204+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:03:45.374+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:45.373+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-9nyzf541 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T07:03:45.750+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:45.749+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T07:03:46.280+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:03:46.362+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:46.362+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T07:03:46.392+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:46.392+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T07:03:46.408+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 6.261 seconds
[2022-11-29T07:04:17.447+0000] {processor.py:154} INFO - Started process (PID=170) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:04:17.464+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:04:17.481+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:04:17.481+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:04:26.271+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:04:26.271+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-vqxq__oz because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T07:04:26.483+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:04:26.482+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T07:04:26.822+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:04:26.865+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:04:26.864+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T07:04:26.896+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:04:26.896+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T07:04:26.914+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 9.576 seconds
[2022-11-29T07:04:57.588+0000] {processor.py:154} INFO - Started process (PID=202) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:04:57.593+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:04:57.595+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:04:57.595+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:05:33.837+0000] {processor.py:154} INFO - Started process (PID=226) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:05:33.903+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:05:33.905+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:05:33.905+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:06:15.919+0000] {processor.py:154} INFO - Started process (PID=249) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:06:15.925+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:06:15.936+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:06:15.936+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:06:56.263+0000] {processor.py:154} INFO - Started process (PID=271) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:06:56.280+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:06:56.284+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:06:56.284+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:07:40.568+0000] {processor.py:154} INFO - Started process (PID=295) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:07:40.582+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:07:40.584+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:07:40.584+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:08:03.231+0000] {processor.py:154} INFO - Started process (PID=309) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:08:03.261+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:08:03.276+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:08:03.266+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:08:20.964+0000] {processor.py:154} INFO - Started process (PID=322) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:08:20.985+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:08:20.987+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:08:20.987+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:08:58.870+0000] {processor.py:154} INFO - Started process (PID=342) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:08:58.912+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:08:58.928+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:08:58.928+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:09:36.697+0000] {processor.py:154} INFO - Started process (PID=365) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:09:36.737+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:09:36.744+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:09:36.744+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:10:20.133+0000] {processor.py:154} INFO - Started process (PID=390) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:10:20.961+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:10:21.870+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:10:21.689+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:11:01.464+0000] {processor.py:154} INFO - Started process (PID=414) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:11:01.481+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:11:01.487+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:11:01.487+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:11:45.139+0000] {processor.py:154} INFO - Started process (PID=436) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:11:46.160+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:11:46.181+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:11:46.181+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:12:07.568+0000] {processor.py:154} INFO - Started process (PID=449) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:12:07.606+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:12:07.612+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:12:07.611+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:12:48.339+0000] {processor.py:154} INFO - Started process (PID=475) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:12:48.396+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:12:48.399+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:12:48.399+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:13:32.673+0000] {processor.py:154} INFO - Started process (PID=498) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:13:32.686+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:13:32.692+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:13:32.692+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:14:06.582+0000] {processor.py:154} INFO - Started process (PID=522) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:14:06.627+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:14:06.631+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:14:06.631+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:14:45.149+0000] {processor.py:154} INFO - Started process (PID=536) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:14:45.189+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:14:45.202+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:14:45.202+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:16:57.559+0000] {processor.py:154} INFO - Started process (PID=545) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:16:57.591+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:16:57.613+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:16:57.613+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:17:28.117+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:17:28.091+0000] {timeout.py:68} ERROR - Process timed out, PID: 545
[2022-11-29T07:17:28.174+0000] {logging_mixin.py:137} WARNING - Exception ignored in: <module 'collections.abc' from '/usr/local/lib/python3.7/collections/abc.py'>
[2022-11-29T07:17:28.176+0000] {logging_mixin.py:137} WARNING - Traceback (most recent call last):
[2022-11-29T07:17:28.179+0000] {logging_mixin.py:137} WARNING -   File "<string>", line 1, in <module>
[2022-11-29T07:17:28.196+0000] {logging_mixin.py:137} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2022-11-29T07:17:28.228+0000] {logging_mixin.py:137} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2022-11-29T07:17:28.262+0000] {logging_mixin.py:137} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 545
[2022-11-29T07:17:28.703+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.7/importlib/_bootstrap.py:219 RuntimeWarning: Cython module failed to patch module with custom type
[2022-11-29T07:17:50.140+0000] {processor.py:154} INFO - Started process (PID=565) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:17:50.181+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:17:50.262+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:17:50.244+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:18:21.682+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:18:20.709+0000] {timeout.py:68} ERROR - Process timed out, PID: 565
[2022-11-29T07:18:23.335+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:18:21.838+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/.local/lib/python3.7/site-packages/pandas/core/strings/__init__.abi3.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 7, in <module>
    from pandas.core.arrays.categorical import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 113, in <module>
    from pandas.core.strings.object_array import ObjectStringArrayMixin
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1383, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 565
[2022-11-29T07:18:23.586+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:18:29.584+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 39.686 seconds
[2022-11-29T07:19:06.125+0000] {processor.py:154} INFO - Started process (PID=605) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:19:06.259+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:19:06.307+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:19:06.307+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:19:38.458+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:19:37.863+0000] {timeout.py:68} ERROR - Process timed out, PID: 605
[2022-11-29T07:19:41.265+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:19:39.357+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 7, in <module>
    from pandas.core.util.hashing import (  # noqa
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 605
[2022-11-29T07:19:41.650+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:19:55.494+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 49.668 seconds
[2022-11-29T07:20:07.575+0000] {processor.py:154} INFO - Started process (PID=625) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:20:07.879+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:20:08.307+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:20:08.247+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:20:41.038+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:20:40.602+0000] {timeout.py:68} ERROR - Process timed out, PID: 625
[2022-11-29T07:20:42.678+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:20:41.813+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1596, in init pandas._libs.tslibs.timedeltas
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1328, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 625
[2022-11-29T07:20:42.937+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:21:29.178+0000] {processor.py:154} INFO - Started process (PID=664) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:21:30.442+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:21:31.343+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:21:31.332+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:22:02.917+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:22:02.707+0000] {timeout.py:68} ERROR - Process timed out, PID: 664
[2022-11-29T07:22:05.430+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:22:04.779+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timedeltas.pyx", line 61, in init pandas._libs.tslibs.timedeltas
  File "pandas/_libs/tslibs/fields.pyx", line 22, in init pandas._libs.tslibs.fields
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 664
[2022-11-29T07:22:07.094+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:35:36.317+0000] {processor.py:154} INFO - Started process (PID=735) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:35:37.063+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T07:35:37.951+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:35:37.359+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T07:36:17.852+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:36:15.206+0000] {timeout.py:68} ERROR - Process timed out, PID: 735
[2022-11-29T07:52:19.927+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:52:12.870+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 7, in <module>
    from pandas.core.util.hashing import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/util/hashing.py", line 17, in <module>
    from pandas._libs import lib
  File "pandas/_libs/lib.pyx", line 86, in init pandas._libs.lib
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 735
[2022-11-29T07:52:33.045+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T09:37:16.544+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 196.812 seconds
[2022-11-29T09:41:57.603+0000] {processor.py:154} INFO - Started process (PID=99) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T09:41:57.654+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T09:41:57.720+0000] {logging_mixin.py:137} INFO - [2022-11-29T09:41:57.720+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T09:42:28.506+0000] {logging_mixin.py:137} INFO - [2022-11-29T09:42:28.136+0000] {timeout.py:68} ERROR - Process timed out, PID: 99
[2022-11-29T09:42:29.193+0000] {logging_mixin.py:137} INFO - [2022-11-29T09:42:28.691+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 4, in <module>
    from packages.ft_perceptron import *
  File "/opt/airflow/dags/packages/ft_perceptron.py", line 2, in <module>
    from packages.source.net import NN, Linear, Relu
  File "/opt/airflow/dags/packages/source/net.py", line 4, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 413, in <module>
    from ._linprog import linprog, linprog_verbose_callback
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_linprog.py", line 23, in <module>
    from ._linprog_ip import _linprog_ip
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_linprog_ip.py", line 27, in <module>
    from ._linprog_util import _postsolve
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 99
[2022-11-29T09:42:29.631+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T09:42:32.286+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 34.805 seconds
[2022-11-29T16:30:14.136+0000] {processor.py:154} INFO - Started process (PID=136) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:30:14.185+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T16:30:14.241+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:30:14.240+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:30:44.644+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:30:44.464+0000] {timeout.py:68} ERROR - Process timed out, PID: 136
[2022-11-29T16:30:44.969+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:30:44.679+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 4, in <module>
    from packages.ft_perceptron import *
  File "/opt/airflow/dags/packages/ft_perceptron.py", line 2, in <module>
    from packages.source.net import NN, Linear, Relu
  File "/opt/airflow/dags/packages/source/net.py", line 4, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 11, in <module>
    from . import _discrete_distns
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_discrete_distns.py", line 19, in <module>
    from .biasedurn import (_PyFishersNCHypergeometric,
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 136
[2022-11-29T16:30:45.349+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:30:47.299+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 33.423 seconds
[2022-11-29T16:31:32.147+0000] {processor.py:154} INFO - Started process (PID=176) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:31:32.317+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T16:31:32.389+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:31:32.372+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:32:05.696+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:32:04.425+0000] {timeout.py:68} ERROR - Process timed out, PID: 176
[2022-11-29T16:32:06.240+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:32:05.750+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.base import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/base.py", line 60, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 55, in <module>
    from pandas.core.ops.methods import add_flex_arithmetic_methods  # noqa:F401
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 176
[2022-11-29T16:32:06.547+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:32:08.547+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 36.903 seconds
[2022-11-29T16:32:55.184+0000] {processor.py:154} INFO - Started process (PID=216) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:32:55.260+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T16:32:55.370+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:32:55.327+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:40:24.086+0000] {processor.py:154} INFO - Started process (PID=69) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:40:24.148+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T16:40:24.197+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:40:24.197+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:40:58.508+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:40:58.198+0000] {timeout.py:68} ERROR - Process timed out, PID: 69
[2022-11-29T16:40:58.945+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:40:58.703+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 20, in <module>
    from pandas.core.arrays.string_arrow import ArrowStringArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/string_arrow.py", line 65, in <module>
    import pyarrow.compute as pc
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 18, in <module>
    from pyarrow._compute import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 69
[2022-11-29T16:40:59.041+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:40:59.732+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 35.702 seconds
[2022-11-29T16:41:41.242+0000] {processor.py:154} INFO - Started process (PID=101) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:41:41.349+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T16:41:41.408+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:41:41.406+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:42:12.350+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:42:11.895+0000] {timeout.py:68} ERROR - Process timed out, PID: 101
[2022-11-29T16:42:13.151+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:42:12.464+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 4, in <module>
    from packages.ft_perceptron import *
  File "/opt/airflow/dags/packages/ft_perceptron.py", line 2, in <module>
    from packages.source.net import NN, Linear, Relu
  File "/opt/airflow/dags/packages/source/net.py", line 4, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 37, in <module>
    from scipy.spatial.distance import cdist
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/__init__.py", line 107, in <module>
    from . import distance, transform
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/transform/__init__.py", line 19, in <module>
    from .rotation import Rotation, Slerp
  File "rotation.pyx", line 5, in init scipy.spatial.transform.rotation
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/transform/_rotation_groups.py", line 2, in <module>
    from scipy.constants import golden as phi
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/constants/__init__.py", line 319, in <module>
    from .codata import *
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 101
[2022-11-29T16:42:13.438+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:42:15.811+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 34.863 seconds
[2022-11-29T16:49:04.909+0000] {processor.py:154} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:49:04.925+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T16:49:04.927+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:49:04.927+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:49:08.003+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:49:08.001+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-nqgm24yw because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T16:49:08.632+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:49:08.630+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T16:49:09.571+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:49:09.840+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:49:09.839+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T16:49:09.909+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:49:09.909+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T16:49:09.960+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 5.064 seconds
[2022-11-29T16:49:56.396+0000] {processor.py:154} INFO - Started process (PID=71) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:49:56.519+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T16:49:56.540+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:49:56.540+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:50:26.823+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:50:26.714+0000] {timeout.py:68} ERROR - Process timed out, PID: 71
[2022-11-29T16:50:27.158+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:50:26.837+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 144, in <module>
    from pandas.core.window import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (  # noqa:F401
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/window/ewm.py", line 11, in <module>
    import pandas._libs.window.aggregations as window_aggregations
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 71
[2022-11-29T16:50:27.689+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:51:03.052+0000] {processor.py:154} INFO - Started process (PID=103) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:51:03.062+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T16:51:03.065+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:03.065+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:51:05.753+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:05.753+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-r8am9928 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T16:51:06.454+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:06.453+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T16:51:07.728+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:51:07.853+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:07.853+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T16:51:07.919+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:07.915+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T16:51:07.992+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 4.947 seconds
[2022-11-29T16:51:39.662+0000] {processor.py:154} INFO - Started process (PID=138) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:51:39.665+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T16:51:39.668+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:39.668+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:51:49.559+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:49.559+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-omw8m3r4 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T16:51:49.832+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:49.831+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T16:51:50.470+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:51:50.533+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:50.533+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T16:51:50.575+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:50.575+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T16:51:50.602+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 10.954 seconds
[2022-11-29T16:52:35.160+0000] {processor.py:154} INFO - Started process (PID=168) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:52:35.603+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T16:52:36.398+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:52:36.393+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:53:09.037+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:53:06.773+0000] {timeout.py:68} ERROR - Process timed out, PID: 168
[2022-11-29T16:53:14.427+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:53:10.073+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 6, in <module>
    import pyarrow as pa
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/__init__.py", line 182, in <module>
    from pyarrow._hdfsio import HdfsFile, have_libhdfs
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1364, in find_spec
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 168
[2022-11-29T16:53:16.399+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:53:23.661+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 48.780 seconds
[2022-11-29T16:54:02.336+0000] {processor.py:154} INFO - Started process (PID=190) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:54:02.482+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T16:54:02.598+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:54:02.552+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:54:33.323+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:54:32.923+0000] {timeout.py:68} ERROR - Process timed out, PID: 190
[2022-11-29T16:54:34.019+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:54:33.439+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 4, in <module>
    from packages.ft_perceptron import *
  File "/opt/airflow/dags/packages/ft_perceptron.py", line 2, in <module>
    from packages.source.net import NN, Linear, Relu
  File "/opt/airflow/dags/packages/source/net.py", line 4, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 400, in <module>
    from .optimize import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 36, in <module>
    from ._numdiff import approx_derivative
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_numdiff.py", line 6, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/linalg/__init__.py", line 114, in <module>
    from .eigen import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/__init__.py", line 9, in <module>
    from .arpack import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/__init__.py", line 20, in <module>
    from .arpack import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 42, in <module>
    from . import _arpack
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 190
[2022-11-29T16:54:34.463+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:54:38.580+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 36.482 seconds
[2022-11-29T16:55:28.266+0000] {processor.py:154} INFO - Started process (PID=195) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:55:28.695+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T16:55:28.761+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:55:28.760+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:56:01.049+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:56:00.878+0000] {timeout.py:68} ERROR - Process timed out, PID: 195
[2022-11-29T16:56:01.116+0000] {logging_mixin.py:137} WARNING - Exception ignored in: <module 'collections.abc' from '/usr/local/lib/python3.7/collections/abc.py'>
[2022-11-29T16:56:01.128+0000] {logging_mixin.py:137} WARNING - Traceback (most recent call last):
[2022-11-29T16:56:01.147+0000] {logging_mixin.py:137} WARNING -   File "<string>", line 1, in <module>
[2022-11-29T16:56:01.288+0000] {logging_mixin.py:137} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2022-11-29T16:56:01.332+0000] {logging_mixin.py:137} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2022-11-29T16:56:01.341+0000] {logging_mixin.py:137} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 195
[2022-11-29T16:56:02.485+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.7/importlib/_bootstrap.py:219 RuntimeWarning: Cython module failed to patch module with custom type
[2022-11-29T16:56:27.685+0000] {processor.py:154} INFO - Started process (PID=200) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:56:27.733+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T16:56:27.795+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:56:27.793+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:58:33.117+0000] {processor.py:154} INFO - Started process (PID=247) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:58:33.141+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T16:58:33.180+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:58:33.177+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T16:59:05.481+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:59:05.070+0000] {timeout.py:68} ERROR - Process timed out, PID: 247
[2022-11-29T16:59:21.941+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:59:08.483+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/timezones.pyx", line 43, in init pandas._libs.tslibs.timezones
  File "/home/airflow/.local/lib/python3.7/site-packages/dateutil/tz/tz.py", line 1557, in __call__
    rv = self.nocache(name=name)
  File "/home/airflow/.local/lib/python3.7/site-packages/dateutil/tz/tz.py", line 1640, in nocache
    tz = tzfile(filepath)
  File "/home/airflow/.local/lib/python3.7/site-packages/dateutil/tz/tz.py", line 462, in __init__
    if isinstance(fileobj, string_types):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 247
[2022-11-29T16:59:24.513+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T17:01:23.688+0000] {processor.py:154} INFO - Started process (PID=272) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T17:01:23.995+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T17:01:24.517+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:01:24.300+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T17:01:56.842+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:01:56.140+0000] {timeout.py:68} ERROR - Process timed out, PID: 272
[2022-11-29T17:01:59.630+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:01:57.860+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 49, in <module>
    from pandas._libs.tslibs.period import (
  File "pandas/_libs/tslibs/period.pyx", line 1, in init pandas._libs.tslibs.period
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 272
[2022-11-29T17:02:01.364+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T17:03:20.654+0000] {processor.py:154} INFO - Started process (PID=318) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T17:03:20.923+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T17:03:21.534+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:03:21.320+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T17:03:53.642+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:03:53.380+0000] {timeout.py:68} ERROR - Process timed out, PID: 318
[2022-11-29T17:03:55.740+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:03:54.199+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 7, in <module>
    from pandas.core.util.hashing import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/util/hashing.py", line 17, in <module>
    from pandas._libs import lib
  File "pandas/_libs/lib.pyx", line 1, in init pandas._libs.lib
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 318
[2022-11-29T17:03:57.661+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T17:05:35.799+0000] {processor.py:154} INFO - Started process (PID=374) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T17:05:36.298+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T17:05:36.957+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:05:36.727+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T17:06:09.203+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:06:08.622+0000] {timeout.py:68} ERROR - Process timed out, PID: 374
[2022-11-29T17:07:48.210+0000] {processor.py:154} INFO - Started process (PID=416) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-29T17:07:52.601+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-29T17:07:56.173+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:07:54.986+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
