[2022-11-27T19:24:31.256+0000] {processor.py:154} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:24:31.291+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-27T19:24:31.301+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:24:31.301+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:24:38.148+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:24:38.140+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-hx_kfehc because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-27T19:24:39.510+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:24:39.509+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-27T19:24:43.896+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:24:45.119+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:24:45.118+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-27T19:24:45.580+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:24:45.580+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-27T00:00:00+00:00, run_after=2022-11-28T00:00:00+00:00
[2022-11-27T19:24:45.835+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 14.614 seconds
[2022-11-27T19:25:18.057+0000] {processor.py:154} INFO - Started process (PID=83) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:25:18.080+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-27T19:25:18.093+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:25:18.092+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:25:57.701+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:25:57.695+0000] {timeout.py:68} ERROR - Process timed out, PID: 83
[2022-11-27T19:25:57.860+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:25:57.745+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 4, in <module>
    from packages.ft_perceptron import *
  File "/opt/airflow/dags/packages/ft_perceptron.py", line 2, in <module>
    from packages.source.net import NN, Linear, Relu
  File "/opt/airflow/dags/packages/source/net.py", line 4, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_continuous_distns.py", line 9526, in <module>
    pairs = list(globals().copy().items())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 83
[2022-11-27T19:25:57.936+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:25:58.112+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 40.172 seconds
[2022-11-27T19:26:29.832+0000] {processor.py:154} INFO - Started process (PID=116) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:26:29.843+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-27T19:26:29.858+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:26:29.857+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:26:51.335+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:26:51.334+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-r3868_lt because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-27T19:26:51.583+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:26:51.583+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-27T19:26:51.988+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:26:52.115+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:26:52.114+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-27T19:26:52.155+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:26:52.155+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-27T00:00:00+00:00, run_after=2022-11-28T00:00:00+00:00
[2022-11-27T19:26:52.199+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 22.387 seconds
[2022-11-27T19:27:23.647+0000] {processor.py:154} INFO - Started process (PID=152) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:27:23.873+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-27T19:27:24.342+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:27:24.005+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:27:55.984+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:27:55.970+0000] {timeout.py:68} ERROR - Process timed out, PID: 152
[2022-11-27T19:27:56.519+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:27:56.136+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 6, in <module>
    import pyarrow as pa
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 152
[2022-11-27T19:27:56.723+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:27:59.450+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 36.238 seconds
[2022-11-27T19:29:13.718+0000] {processor.py:154} INFO - Started process (PID=189) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:29:14.196+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-27T19:29:14.758+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:29:14.733+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:29:49.844+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:29:49.689+0000] {timeout.py:68} ERROR - Process timed out, PID: 189
[2022-11-27T19:29:51.217+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:29:50.278+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 189
[2022-11-27T19:29:51.803+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:30:45.440+0000] {processor.py:154} INFO - Started process (PID=230) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:30:49.069+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-27T19:30:53.912+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:30:53.017+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:31:33.171+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:31:33.090+0000] {timeout.py:68} ERROR - Process timed out, PID: 230
[2022-11-27T19:31:34.269+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:31:33.237+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 2, in <module>
    from airflow.operators.python import PythonOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 83, in <module>
    class PythonOperator(BaseOperator):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 428, in __new__
    new_cls = super().__new__(cls, name, bases, namespace, **kwargs)
  File "/usr/local/lib/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 230
[2022-11-27T19:31:35.491+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:33:48.172+0000] {processor.py:154} INFO - Started process (PID=260) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-27T19:33:50.689+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-27T19:33:54.432+0000] {logging_mixin.py:137} INFO - [2022-11-27T19:33:54.176+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
