[2022-12-01T11:05:46.570+0000] {processor.py:154} INFO - Started process (PID=60) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:05:46.586+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T11:05:46.589+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:05:46.589+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:05:51.626+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:05:52.933+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:05:52.928+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T11:05:53.102+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:05:53.101+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-30T00:00:00+00:00, run_after=2022-12-01T00:00:00+00:00
[2022-12-01T11:05:53.188+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 6.667 seconds
[2022-12-01T11:06:28.901+0000] {processor.py:154} INFO - Started process (PID=98) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:06:28.905+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T11:06:28.907+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:06:28.907+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:06:29.573+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:06:29.916+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:06:29.908+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T11:06:29.999+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:06:29.999+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T11:06:30.065+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 1.205 seconds
[2022-12-01T11:07:34.388+0000] {processor.py:154} INFO - Started process (PID=143) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:07:34.397+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T11:07:34.400+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:07:34.400+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:07:39.430+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:07:39.769+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:07:39.768+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T11:07:39.921+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:07:39.920+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T11:07:40.346+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 5.974 seconds
[2022-12-01T11:08:11.100+0000] {processor.py:154} INFO - Started process (PID=170) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:08:11.102+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T11:08:11.103+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:08:11.103+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:08:11.462+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:08:11.513+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:08:11.513+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T11:08:11.548+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:08:11.548+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T11:08:11.582+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.486 seconds
[2022-12-01T11:09:18.663+0000] {processor.py:154} INFO - Started process (PID=199) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:09:18.784+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T11:09:18.876+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:09:18.875+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:09:49.141+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:09:48.508+0000] {timeout.py:68} ERROR - Process timed out, PID: 199
[2022-12-01T11:09:54.017+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:09:49.998+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 6, in <module>
    import pyarrow as pa
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
  File "pyarrow/config.pxi", line 20, in init pyarrow.lib
  File "<frozen importlib._bootstrap>", line 1009, in _handle_fromlist
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 199
[2022-12-01T11:09:54.233+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:09:57.908+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 40.422 seconds
[2022-12-01T11:10:47.626+0000] {processor.py:154} INFO - Started process (PID=241) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:10:47.768+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T11:10:47.885+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:10:47.883+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:11:22.584+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:11:21.442+0000] {timeout.py:68} ERROR - Process timed out, PID: 241
[2022-12-01T11:11:23.462+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:11:22.758+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 20, in <module>
    from pandas.core.arrays.string_arrow import ArrowStringArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/string_arrow.py", line 65, in <module>
    import pyarrow.compute as pc
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 18, in <module>
    from pyarrow._compute import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 241
[2022-12-01T11:11:24.605+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:11:32.758+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 45.469 seconds
[2022-12-01T11:12:32.094+0000] {processor.py:154} INFO - Started process (PID=287) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:12:33.319+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T11:12:35.913+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:12:35.354+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:13:09.665+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:13:09.587+0000] {timeout.py:68} ERROR - Process timed out, PID: 287
[2022-12-01T11:13:11.707+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:13:10.283+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 287
[2022-12-01T11:13:12.498+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:13:17.977+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 49.041 seconds
[2022-12-01T11:13:56.166+0000] {processor.py:154} INFO - Started process (PID=338) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:13:56.757+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T11:13:57.162+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:13:57.162+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:14:30.850+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:14:28.112+0000] {timeout.py:68} ERROR - Process timed out, PID: 338
[2022-12-01T11:14:36.193+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:14:34.348+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timedeltas.pyx", line 61, in init pandas._libs.tslibs.timedeltas
  File "pandas/_libs/tslibs/fields.pyx", line 49, in init pandas._libs.tslibs.fields
  File "pandas/_libs/tslibs/strptime.pyx", line 633, in init pandas._libs.tslibs.strptime
  File "pandas/_libs/tslibs/strptime.pyx", line 564, in pandas._libs.tslibs.strptime.TimeRE.__init__
  File "pandas/_libs/tslibs/strptime.pyx", line 598, in genexpr
  File "pandas/_libs/tslibs/strptime.pyx", line 598, in genexpr
  File "/usr/local/lib/python3.7/re.py", line 254, in escape
    def escape(pattern):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 338
[2022-12-01T11:14:37.371+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:15:26.395+0000] {processor.py:154} INFO - Started process (PID=372) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T11:15:29.348+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T11:15:31.334+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:15:29.720+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:27:11.545+0000] {processor.py:154} INFO - Started process (PID=67) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:27:11.605+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T12:27:11.704+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:27:11.690+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:27:19.313+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:27:32.017+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:27:31.890+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T12:27:32.816+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:27:32.779+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T12:27:33.387+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 22.173 seconds
[2022-12-01T12:28:29.138+0000] {processor.py:154} INFO - Started process (PID=97) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:28:29.195+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T12:28:29.210+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:28:29.210+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:28:36.813+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:28:37.842+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:28:37.817+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T12:28:38.629+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:28:38.605+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T12:28:39.044+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 10.194 seconds
[2022-12-01T12:29:14.247+0000] {processor.py:154} INFO - Started process (PID=130) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:29:14.267+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T12:29:14.279+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:29:14.277+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:29:44.954+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:29:44.531+0000] {timeout.py:68} ERROR - Process timed out, PID: 130
[2022-12-01T12:29:45.265+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:29:45.009+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 456, in <module>
    class DataFrame(NDFrame, OpsMixin):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 4750, in DataFrame
    def set_axis(self, labels, axis: Axis = 0, inplace: bool = False):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 286, in decorate
    def decorate(func):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 130
[2022-12-01T12:29:45.711+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:29:46.773+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 32.575 seconds
[2022-12-01T12:30:18.780+0000] {processor.py:154} INFO - Started process (PID=169) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:30:18.783+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T12:30:18.786+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:30:18.785+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:30:19.206+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:30:19.280+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:30:19.279+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T12:30:19.321+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:30:19.320+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T12:30:19.355+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.582 seconds
[2022-12-01T12:31:17.352+0000] {processor.py:154} INFO - Started process (PID=192) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:31:17.524+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T12:31:17.540+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:31:17.539+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:32:31.764+0000] {processor.py:154} INFO - Started process (PID=223) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:32:31.852+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T12:32:31.934+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:32:31.921+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:33:05.320+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:33:02.181+0000] {timeout.py:68} ERROR - Process timed out, PID: 223
[2022-12-01T12:33:08.040+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:33:06.384+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 7, in <module>
    from pandas.core.util.hashing import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/util/hashing.py", line 17, in <module>
    from pandas._libs import lib
  File "pandas/_libs/lib.pyx", line 1, in init pandas._libs.lib
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 223
[2022-12-01T12:33:08.122+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:33:57.534+0000] {processor.py:154} INFO - Started process (PID=260) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:33:57.577+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T12:33:57.693+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:33:57.680+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:34:28.742+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:34:27.837+0000] {timeout.py:68} ERROR - Process timed out, PID: 260
[2022-12-01T12:34:30.130+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:34:28.991+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 11, in <module>
    from pandas.core.arrays.interval import IntervalArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/interval.py", line 82, in <module>
    from pandas.core.indexes.base import ensure_index
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 90, in <module>
    from pandas.core.dtypes.concat import concat_compat
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/concat.py", line 26, in <module>
    from pandas.core.arrays.sparse import SparseArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/sparse/__init__.py", line 3, in <module>
    from pandas.core.arrays.sparse.accessor import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/sparse/accessor.py", line 13, in <module>
    from pandas.core.arrays.sparse.array import SparseArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/sparse/array.py", line 78, in <module>
    import pandas.io.formats.printing as printing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/printing.py", line 546, in <module>
    class PrettyDict(Dict[_KT, _VT]):
  File "/usr/local/lib/python3.7/typing.py", line 251, in inner
    return cached(*args, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 260
[2022-12-01T12:34:31.621+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:34:40.669+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 43.945 seconds
[2022-12-01T12:35:45.212+0000] {processor.py:154} INFO - Started process (PID=301) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:35:46.283+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T12:35:46.773+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:35:46.772+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:36:20.096+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:36:19.424+0000] {timeout.py:68} ERROR - Process timed out, PID: 301
[2022-12-01T12:36:24.719+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:36:20.829+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 301
[2022-12-01T12:42:09.417+0000] {processor.py:154} INFO - Started process (PID=399) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:42:11.219+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T12:42:15.168+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:42:13.713+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:42:54.341+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:42:51.201+0000] {timeout.py:68} ERROR - Process timed out, PID: 399
[2022-12-01T12:42:59.388+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:42:56.562+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 399
[2022-12-01T12:43:03.881+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:45:46.302+0000] {processor.py:154} INFO - Started process (PID=477) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T12:45:48.624+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T12:45:51.144+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:45:50.562+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:16:57.668+0000] {processor.py:154} INFO - Started process (PID=58) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:16:57.705+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:16:57.784+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:16:57.783+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:17:53.246+0000] {processor.py:154} INFO - Started process (PID=96) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:17:53.252+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:17:53.269+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:17:53.269+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:18:34.270+0000] {processor.py:154} INFO - Started process (PID=123) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:18:34.273+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:18:34.276+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:18:34.275+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:18:34.634+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:18:34.729+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:18:34.729+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:18:34.756+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:18:34.756+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:18:34.778+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.520 seconds
[2022-12-01T13:19:23.583+0000] {processor.py:154} INFO - Started process (PID=160) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:19:23.585+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:19:23.586+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:19:23.586+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:19:23.846+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:19:23.893+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:19:23.892+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:19:23.918+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:19:23.917+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:19:23.933+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.355 seconds
[2022-12-01T13:20:10.905+0000] {processor.py:154} INFO - Started process (PID=195) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:20:10.909+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:20:10.914+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:20:10.913+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:20:11.599+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:20:11.758+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:20:11.757+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:20:11.836+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:20:11.836+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:20:11.889+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 1.001 seconds
[2022-12-01T13:21:22.659+0000] {processor.py:154} INFO - Started process (PID=234) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:21:22.867+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:21:22.948+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:21:22.933+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:21:40.518+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:21:43.493+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:21:43.491+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:21:44.291+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:21:44.283+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:21:44.441+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 22.648 seconds
[2022-12-01T13:22:24.080+0000] {processor.py:154} INFO - Started process (PID=269) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:22:24.102+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:22:24.123+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:22:24.122+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:22:27.098+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:22:27.518+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:22:27.516+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:22:27.577+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:22:27.576+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:22:27.621+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 3.643 seconds
[2022-12-01T13:23:37.644+0000] {processor.py:154} INFO - Started process (PID=299) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:23:37.668+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:23:37.674+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:23:37.673+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:24:42.796+0000] {processor.py:154} INFO - Started process (PID=333) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:24:42.907+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:24:42.910+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:24:42.910+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:24:55.437+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:25:00.857+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:25:00.772+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:25:02.717+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:25:02.700+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:25:05.617+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 23.073 seconds
[2022-12-01T13:25:56.901+0000] {processor.py:154} INFO - Started process (PID=365) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:25:57.215+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:25:57.416+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:25:57.345+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:26:16.585+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:26:19.538+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:26:19.525+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:26:20.845+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:26:20.832+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:26:21.125+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 24.671 seconds
[2022-12-01T13:26:56.455+0000] {processor.py:154} INFO - Started process (PID=397) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:26:56.488+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:26:56.517+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:26:56.516+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:27:03.228+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:27:03.793+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:27:03.791+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:27:03.959+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:27:03.958+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:27:04.059+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 7.652 seconds
[2022-12-01T13:27:35.503+0000] {processor.py:154} INFO - Started process (PID=423) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:27:35.540+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:27:35.574+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:27:35.555+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:28:29.887+0000] {processor.py:154} INFO - Started process (PID=453) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:28:30.600+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:28:30.881+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:28:30.661+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:28:44.209+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:28:47.041+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:28:47.002+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:28:49.172+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:28:49.166+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:28:49.859+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 21.578 seconds
[2022-12-01T13:29:22.517+0000] {processor.py:154} INFO - Started process (PID=487) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:29:22.570+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:29:23.187+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:29:23.162+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:29:50.967+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:29:52.558+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:29:52.549+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:29:53.281+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:29:53.268+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:29:53.625+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 31.341 seconds
[2022-12-01T13:30:25.637+0000] {processor.py:154} INFO - Started process (PID=524) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:30:25.650+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:30:25.654+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:30:25.653+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:30:28.658+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:30:29.132+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:30:29.129+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:30:29.429+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:30:29.428+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:30:29.582+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 3.977 seconds
[2022-12-01T13:31:00.338+0000] {processor.py:154} INFO - Started process (PID=546) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:31:01.005+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:31:01.034+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:31:01.033+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:31:23.799+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:31:24.862+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:31:24.852+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:31:25.323+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:31:25.315+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:31:25.529+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 25.262 seconds
[2022-12-01T13:31:56.430+0000] {processor.py:154} INFO - Started process (PID=582) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:31:56.471+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:31:56.572+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:31:56.533+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:32:29.161+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:32:29.067+0000] {timeout.py:68} ERROR - Process timed out, PID: 582
[2022-12-01T13:32:29.346+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:32:29.178+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 20, in <module>
    from pandas.core.arrays.string_arrow import ArrowStringArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/string_arrow.py", line 65, in <module>
    import pyarrow.compute as pc
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 18, in <module>
    from pyarrow._compute import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 582
[2022-12-01T13:32:29.403+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:32:30.089+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 33.298 seconds
[2022-12-01T13:33:00.885+0000] {processor.py:154} INFO - Started process (PID=616) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:33:00.900+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:33:00.906+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:33:00.905+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:33:02.351+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:33:02.784+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:33:02.782+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:33:30.805+0000] {processor.py:154} INFO - Started process (PID=639) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:33:30.875+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:33:30.962+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:33:30.947+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:34:35.671+0000] {processor.py:154} INFO - Started process (PID=683) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:34:35.675+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:34:35.677+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:35.677+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:34:36.009+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:34:36.052+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:36.052+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:34:36.080+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:36.080+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:34:36.096+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.439 seconds
[2022-12-01T13:35:38.249+0000] {processor.py:154} INFO - Started process (PID=715) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:35:38.254+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:35:38.258+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:35:38.258+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:35:39.161+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:35:39.345+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:35:39.344+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:35:39.405+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:35:39.405+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:35:39.498+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 1.260 seconds
[2022-12-01T13:37:10.072+0000] {processor.py:154} INFO - Started process (PID=745) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:37:10.236+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:37:10.630+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:37:10.509+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:37:41.941+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:37:41.800+0000] {timeout.py:68} ERROR - Process timed out, PID: 745
[2022-12-01T13:37:45.027+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:37:44.424+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 35, in init pandas._libs.tslibs.offsets
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 745
[2022-12-01T13:37:45.186+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:37:49.381+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 40.184 seconds
[2022-12-01T13:38:34.234+0000] {processor.py:154} INFO - Started process (PID=784) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:38:34.347+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:38:34.439+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:38:34.407+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:39:05.473+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:39:04.593+0000] {timeout.py:68} ERROR - Process timed out, PID: 784
[2022-12-01T13:39:06.418+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:39:05.505+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 7, in <module>
    from pandas.core.arrays.categorical import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 98, in <module>
    from pandas.core.arrays._mixins import NDArrayBackedExtensionArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/_mixins.py", line 45, in <module>
    "NDArrayBackedExtensionArrayT", bound="NDArrayBackedExtensionArray"
  File "/usr/local/lib/python3.7/typing.py", line 549, in __init__
    self.__bound__ = _type_check(bound, "Bound must be a type.")
  File "/usr/local/lib/python3.7/typing.py", line 132, in _type_check
    return ForwardRef(arg)
  File "/usr/local/lib/python3.7/typing.py", line 449, in __init__
    code = compile(arg, '<string>', 'eval')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 784
[2022-12-01T13:39:07.468+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:40:27.409+0000] {processor.py:154} INFO - Started process (PID=839) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:40:28.738+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:40:32.933+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:40:32.395+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:41:04.464+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:41:04.272+0000] {timeout.py:68} ERROR - Process timed out, PID: 839
[2022-12-01T13:41:07.312+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:41:05.002+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/timezones.pyx", line 43, in init pandas._libs.tslibs.timezones
  File "/home/airflow/.local/lib/python3.7/site-packages/dateutil/tz/tz.py", line 1567, in __call__
    self.__instances[name] = rv
  File "/usr/local/lib/python3.7/weakref.py", line 168, in __setitem__
    self.data[key] = KeyedRef(value, self._remove, key)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 839
[2022-12-01T13:41:09.021+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:42:20.172+0000] {processor.py:154} INFO - Started process (PID=871) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:42:20.936+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:42:22.384+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:42:21.913+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:43:34.828+0000] {processor.py:154} INFO - Started process (PID=909) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:43:35.486+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:43:37.052+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:43:36.467+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:44:08.994+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:44:08.101+0000] {timeout.py:68} ERROR - Process timed out, PID: 909
[2022-12-01T13:46:07.064+0000] {processor.py:154} INFO - Started process (PID=939) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:46:08.174+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:46:08.704+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:46:08.703+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:50:27.936+0000] {processor.py:154} INFO - Started process (PID=49) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:50:27.943+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:50:27.946+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:50:27.945+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:50:28.507+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:50:28.747+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:50:28.745+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:50:28.835+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:50:28.834+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:50:28.884+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.958 seconds
[2022-12-01T13:51:05.969+0000] {processor.py:154} INFO - Started process (PID=85) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:51:06.041+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:51:06.065+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:06.065+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:51:43.770+0000] {processor.py:154} INFO - Started process (PID=112) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:51:43.776+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T13:51:43.780+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:43.780+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:51:44.513+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T13:51:44.783+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:44.782+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:51:44.828+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:44.828+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:51:44.847+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 1.086 seconds
[2022-12-01T14:00:13.054+0000] {processor.py:154} INFO - Started process (PID=139) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:00:13.140+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T14:00:13.153+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:00:13.153+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:00:43.373+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:00:43.057+0000] {timeout.py:68} ERROR - Process timed out, PID: 139
[2022-12-01T14:00:43.975+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:00:43.572+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 30, in init pandas._libs.missing
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 139
[2022-12-01T14:00:44.988+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:02:05.658+0000] {processor.py:154} INFO - Started process (PID=156) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:02:05.834+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T14:02:06.063+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:02:06.060+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:02:36.993+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:02:36.740+0000] {timeout.py:68} ERROR - Process timed out, PID: 156
[2022-12-01T14:02:40.644+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:02:37.173+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timestamps.pyx", line 1, in init pandas._libs.tslibs.timestamps
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 156
[2022-12-01T14:02:42.321+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:03:50.588+0000] {processor.py:154} INFO - Started process (PID=160) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:03:51.949+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T14:03:53.748+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:03:53.663+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:04:28.176+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:04:28.076+0000] {timeout.py:68} ERROR - Process timed out, PID: 160
[2022-12-01T14:04:28.645+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:04:28.355+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timedeltas.pyx", line 61, in init pandas._libs.tslibs.timedeltas
  File "pandas/_libs/tslibs/fields.pyx", line 49, in init pandas._libs.tslibs.fields
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 160
[2022-12-01T14:04:28.744+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:04:56.024+0000] {processor.py:154} INFO - Started process (PID=163) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:04:56.048+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T14:04:56.100+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:04:56.099+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:05:28.281+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:05:26.550+0000] {timeout.py:68} ERROR - Process timed out, PID: 163
[2022-12-01T14:05:29.831+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:05:28.520+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.base import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/base.py", line 60, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 32, in <module>
    from pandas.core.ops.array_ops import (  # noqa:F401
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 48, in <module>
    import pandas.core.computation.expressions as expressions
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1272, in find_spec
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 163
[2022-12-01T14:05:31.234+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:05:52.019+0000] {processor.py:154} INFO - Started process (PID=166) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:05:52.905+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T14:05:54.019+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:05:53.794+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:06:26.165+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:06:26.127+0000] {timeout.py:68} ERROR - Process timed out, PID: 166
[2022-12-01T14:06:30.423+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:06:29.165+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1595, in init pandas._libs.tslibs.timedeltas
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/core/getlimits.py", line 516, in __init__
    self.dtype = numeric.dtype(int_type)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 166
[2022-12-01T14:06:30.861+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:06:34.360+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 43.905 seconds
[2022-12-01T14:07:19.057+0000] {processor.py:154} INFO - Started process (PID=177) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:07:20.014+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T14:07:21.000+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:07:20.876+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:07:56.020+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:07:54.729+0000] {timeout.py:68} ERROR - Process timed out, PID: 177
[2022-12-01T14:08:04.963+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:07:56.522+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 6, in <module>
    import pyarrow as pa
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
  File "pyarrow/compat.pxi", line 49, in init pyarrow.lib
  File "/home/airflow/.local/lib/python3.7/site-packages/cloudpickle/__init__.py", line 1, in <module>
    from cloudpickle.cloudpickle import *  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 56, in <module>
    from .compat import pickle
  File "/home/airflow/.local/lib/python3.7/site-packages/cloudpickle/compat.py", line 6, in <module>
    import pickle5 as pickle  # noqa: F401
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap>", line 861, in __exit__
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 177
[2022-12-01T14:08:28.800+0000] {processor.py:154} INFO - Started process (PID=210) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:08:29.166+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T14:08:29.806+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:08:29.484+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:09:04.595+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:09:04.468+0000] {timeout.py:68} ERROR - Process timed out, PID: 210
[2022-12-01T14:09:04.856+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:09:04.642+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 6, in <module>
    import pyarrow as pa
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
  File "pyarrow/compat.pxi", line 49, in init pyarrow.lib
  File "/home/airflow/.local/lib/python3.7/site-packages/cloudpickle/__init__.py", line 1, in <module>
    from cloudpickle.cloudpickle import *  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 77, in <module>
    CellType = type(f().__closure__[0])
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 210
[2022-12-01T14:09:05.110+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:09:10.763+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 44.008 seconds
[2022-12-01T14:09:19.482+0000] {processor.py:154} INFO - Started process (PID=241) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:09:19.896+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T14:09:20.561+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:09:20.559+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:09:51.634+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:09:51.477+0000] {timeout.py:68} ERROR - Process timed out, PID: 241
[2022-12-01T14:09:52.730+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:09:51.894+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 7, in <module>
    from pandas.core.util.hashing import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/util/hashing.py", line 17, in <module>
    from pandas._libs import lib
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 241
[2022-12-01T14:09:53.119+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:10:01.075+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 42.938 seconds
[2022-12-01T14:11:05.806+0000] {processor.py:154} INFO - Started process (PID=282) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T14:11:06.729+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T14:11:07.553+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:11:07.475+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:52:59.786+0000] {processor.py:154} INFO - Started process (PID=55) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:52:59.805+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T16:52:59.808+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:52:59.808+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:53:01.544+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:53:01.830+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:53:01.829+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T16:53:01.941+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:53:01.941+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T16:53:02.032+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 2.257 seconds
[2022-12-01T16:53:33.096+0000] {processor.py:154} INFO - Started process (PID=85) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:53:33.100+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T16:53:33.102+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:53:33.102+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:53:33.597+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:53:33.655+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:53:33.655+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T16:53:33.703+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:53:33.702+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T16:53:33.725+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.637 seconds
[2022-12-01T16:54:12.541+0000] {processor.py:154} INFO - Started process (PID=117) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:54:12.560+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T16:54:12.569+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:54:12.568+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:55:09.784+0000] {processor.py:154} INFO - Started process (PID=149) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:55:09.916+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T16:55:10.394+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:55:10.294+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:55:40.958+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:55:40.818+0000] {timeout.py:68} ERROR - Process timed out, PID: 149
[2022-12-01T16:55:43.159+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:55:40.992+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 11, in <module>
    from pandas.core.arrays.interval import IntervalArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/interval.py", line 82, in <module>
    from pandas.core.indexes.base import ensure_index
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 21, in <module>
    from pandas._libs import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1394, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 149
[2022-12-01T16:55:43.953+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:55:54.557+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 46.857 seconds
[2022-12-01T16:55:56.535+0000] {processor.py:154} INFO - Started process (PID=170) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:55:56.570+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T16:55:56.601+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:55:56.600+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:56:35.418+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:56:35.321+0000] {timeout.py:68} ERROR - Process timed out, PID: 170
[2022-12-01T16:56:35.906+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:56:35.621+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 6, in <module>
    import pyarrow as pa
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 170
[2022-12-01T16:56:36.104+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:56:39.416+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 43.014 seconds
[2022-12-01T16:57:36.944+0000] {processor.py:154} INFO - Started process (PID=209) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:57:40.335+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T16:57:40.544+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:57:40.543+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:58:12.229+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:58:11.491+0000] {timeout.py:68} ERROR - Process timed out, PID: 209
[2022-12-01T16:58:16.896+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:58:12.606+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 7, in <module>
    from pandas.core.util.hashing import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/util/hashing.py", line 17, in <module>
    from pandas._libs import lib
  File "pandas/_libs/lib.pyx", line 86, in init pandas._libs.lib
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1394, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 209
[2022-12-01T16:58:18.351+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:59:04.124+0000] {processor.py:154} INFO - Started process (PID=248) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:59:04.299+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T16:59:05.030+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:59:04.856+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T16:59:37.972+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:59:37.646+0000] {timeout.py:68} ERROR - Process timed out, PID: 248
[2022-12-01T16:59:40.458+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:59:38.933+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/timezones.pyx", line 43, in init pandas._libs.tslibs.timezones
  File "/home/airflow/.local/lib/python3.7/site-packages/dateutil/tz/tz.py", line 1557, in __call__
    rv = self.nocache(name=name)
  File "/home/airflow/.local/lib/python3.7/site-packages/dateutil/tz/tz.py", line 1635, in nocache
    if not os.path.isfile(filepath):
  File "/usr/local/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 248
[2022-12-01T16:59:41.827+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T17:00:06.124+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 62.334 seconds
[2022-12-01T17:00:43.689+0000] {processor.py:154} INFO - Started process (PID=282) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T17:00:44.903+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T17:00:46.265+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:00:45.409+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T17:01:23.346+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:01:22.815+0000] {timeout.py:68} ERROR - Process timed out, PID: 282
[2022-12-01T17:03:27.346+0000] {processor.py:154} INFO - Started process (PID=328) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T17:03:30.189+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T17:03:43.120+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:03:42.488+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T17:07:49.586+0000] {processor.py:154} INFO - Started process (PID=410) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T17:07:51.847+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T17:07:57.257+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:07:54.249+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T17:23:02.370+0000] {processor.py:154} INFO - Started process (PID=121) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T17:23:02.408+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T17:23:02.419+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:23:02.418+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T17:23:10.398+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-12-01T17:23:14.064+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:23:13.956+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T17:23:15.283+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:23:15.230+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T17:23:15.811+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 13.486 seconds
[2022-12-01T17:26:33.640+0000] {processor.py:154} INFO - Started process (PID=188) to work on /opt/airflow/dags/dag_generate_data.py
[2022-12-01T17:26:39.248+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-12-01T17:26:46.435+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:26:46.030+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
