[2022-12-01T11:05:25.698+0000] {processor.py:154} INFO - Started process (PID=44) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:05:25.724+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T11:05:25.760+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:05:25.760+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:05:37.454+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:05:37.398+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-hsvt3b90 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T11:05:39.972+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:05:39.934+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T11:05:43.340+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:05:44.615+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:05:44.600+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T11:05:44.917+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:05:44.913+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-30T00:00:00+00:00, run_after=2022-12-01T00:00:00+00:00
[2022-12-01T11:05:45.039+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 19.409 seconds
[2022-12-01T11:06:17.139+0000] {processor.py:154} INFO - Started process (PID=81) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:06:17.142+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T11:06:17.146+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:06:17.145+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:06:25.993+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:06:25.992+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-0o75ykyr because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T11:06:26.535+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:06:26.533+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T11:06:27.613+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:06:27.916+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:06:27.915+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T11:06:27.970+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:06:27.970+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T11:06:28.015+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 10.896 seconds
[2022-12-01T11:06:59.332+0000] {processor.py:154} INFO - Started process (PID=119) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:06:59.348+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T11:06:59.359+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:06:59.358+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:07:24.401+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:07:24.399+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ysfq8lu8 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T11:07:28.252+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:07:28.247+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T11:07:29.746+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:07:29.445+0000] {timeout.py:68} ERROR - Process timed out, PID: 119
[2022-12-01T11:07:30.135+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:07:29.772+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 4, in <module>
    from packages.ft_perceptron import *
  File "/opt/airflow/dags/packages/ft_perceptron.py", line 6, in <module>
    from matplotlib import pyplot as plt
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 49, in <module>
    import matplotlib.colorbar
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/colorbar.py", line 21, in <module>
    from matplotlib import _api, collections, cm, colors, contour, ticker
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/contour.py", line 13, in <module>
    from matplotlib.backend_bases import MouseButton
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 54, in <module>
    from matplotlib._enums import JoinStyle, CapStyle
  File "<frozen importlib._bootstrap>", line 1009, in _handle_fromlist
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 119
[2022-12-01T11:07:30.406+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:07:31.483+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 32.193 seconds
[2022-12-01T11:08:04.805+0000] {processor.py:154} INFO - Started process (PID=163) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:08:04.811+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T11:08:04.814+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:08:04.814+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:08:06.995+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:08:06.994+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ly30okkm because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T11:08:07.195+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:08:07.195+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T11:08:07.610+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:08:07.691+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:08:07.691+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T11:08:07.731+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:08:07.731+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T11:08:07.757+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 2.964 seconds
[2022-12-01T11:08:38.537+0000] {processor.py:154} INFO - Started process (PID=188) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:08:38.558+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T11:08:38.566+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:08:38.566+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:09:11.042+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:09:08.756+0000] {timeout.py:68} ERROR - Process timed out, PID: 188
[2022-12-01T11:09:12.428+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:09:11.070+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 6, in <module>
    from pandas.core.arrays.boolean import BooleanArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/boolean.py", line 36, in <module>
    from pandas.core.arrays.masked import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/masked.py", line 46, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/nanops.py", line 624, in <module>
    mask: np.ndarray | None = None,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/nanops.py", line 402, in _datetimelike_compat
    mask: np.ndarray | None = None,
  File "/usr/local/lib/python3.7/functools.py", line 60, in update_wrapper
    getattr(wrapper, attr).update(getattr(wrapped, attr, {}))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 188
[2022-12-01T11:09:12.847+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:09:15.813+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 36.530 seconds
[2022-12-01T11:10:03.701+0000] {processor.py:154} INFO - Started process (PID=221) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:10:03.980+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T11:10:04.737+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:10:04.489+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:10:39.717+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:10:39.612+0000] {timeout.py:68} ERROR - Process timed out, PID: 221
[2022-12-01T11:10:41.271+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:10:40.600+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 35, in init pandas._libs.tslibs.offsets
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 221
[2022-12-01T11:10:42.021+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:10:47.761+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 44.597 seconds
[2022-12-01T11:11:36.937+0000] {processor.py:154} INFO - Started process (PID=272) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:11:37.276+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T11:11:37.854+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:11:37.689+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:12:08.787+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:12:08.618+0000] {timeout.py:68} ERROR - Process timed out, PID: 272
[2022-12-01T11:12:15.310+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:12:09.743+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 272
[2022-12-01T11:12:15.940+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:12:25.735+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 49.533 seconds
[2022-12-01T11:13:00.933+0000] {processor.py:154} INFO - Started process (PID=297) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:13:01.383+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T11:13:01.535+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:13:01.535+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:13:37.142+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:13:37.046+0000] {timeout.py:68} ERROR - Process timed out, PID: 297
[2022-12-01T11:13:37.857+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:13:37.236+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 6, in <module>
    import pyarrow as pa
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 297
[2022-12-01T11:13:38.635+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:13:45.929+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 46.672 seconds
[2022-12-01T11:14:35.300+0000] {processor.py:154} INFO - Started process (PID=347) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:14:35.907+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T11:14:36.099+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:14:36.097+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T11:15:08.719+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:15:07.710+0000] {timeout.py:68} ERROR - Process timed out, PID: 347
[2022-12-01T12:26:39.188+0000] {processor.py:154} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:26:39.193+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T12:26:39.195+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:26:39.195+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:26:54.006+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:26:53.981+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-jypkz5ha because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T12:26:57.071+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:26:57.055+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T12:27:04.059+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:27:08.209+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:27:08.119+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T12:27:08.746+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:27:08.746+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T12:27:09.316+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 30.135 seconds
[2022-12-01T12:27:43.258+0000] {processor.py:154} INFO - Started process (PID=79) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:27:43.263+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T12:27:43.274+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:27:43.274+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:28:19.090+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:28:13.684+0000] {timeout.py:68} ERROR - Process timed out, PID: 79
[2022-12-01T12:28:24.920+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:28:20.016+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 122, in <module>
    from pandas.core.describe import describe_ndframe
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/describe.py", line 37, in <module>
    from pandas.core.reshape.concat import concat
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 45, in <module>
    from pandas.core.internals import concatenate_managers
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/__init__.py", line 1, in <module>
    from pandas.core.internals.api import make_block  # pseudo-public version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/api.py", line 23, in <module>
    from pandas.core.internals.blocks import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 75, in <module>
    import pandas.core.algorithms as algos
  File "<frozen importlib._bootstrap>", line 200, in _lock_unlock_module
  File "<frozen importlib._bootstrap>", line 170, in _get_module_lock
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 79
[2022-12-01T12:28:25.342+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:28:26.493+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 43.321 seconds
[2022-12-01T12:28:58.651+0000] {processor.py:154} INFO - Started process (PID=120) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:28:58.665+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T12:28:58.675+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:28:58.675+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:29:45.726+0000] {processor.py:154} INFO - Started process (PID=141) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:29:45.869+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T12:29:45.905+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:29:45.904+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:30:14.236+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:30:14.236+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-i98pvdu2 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T12:30:15.157+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:30:15.156+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T12:30:16.063+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:30:16.061+0000] {timeout.py:68} ERROR - Process timed out, PID: 141
[2022-12-01T12:30:16.096+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:30:16.067+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 4, in <module>
    from packages.ft_perceptron import *
  File "/opt/airflow/dags/packages/ft_perceptron.py", line 6, in <module>
    from matplotlib import pyplot as plt
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 57, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/figure.py", line 25, in <module>
    from matplotlib import _blocking_input, docstring, projections
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/projections/__init__.py", line 55, in <module>
    from .. import axes, docstring
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/axes/__init__.py", line 1, in <module>
    from ._subplots import *
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/axes/_subplots.py", line 3, in <module>
    from matplotlib.axes._axes import Axes
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 34, in <module>
    from matplotlib.axes._base import (
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 17, in <module>
    import matplotlib.axis as maxis
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/axis.py", line 602, in <module>
    class Axis(martist.Artist):
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 120, in __init_subclass__
    cls._update_set_signature_and_docstring()
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 148, in _update_set_signature_and_docstring
    + kwdoc(cls))
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 1759, in kwdoc
    ai = ArtistInspector(artist)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 1358, in __init__
    self.aliasd = self.get_aliases()
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 1377, in get_aliases
    if not self.is_alias(func):
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 1456, in is_alias
    ds = inspect.getdoc(o)
  File "/usr/local/lib/python3.7/inspect.py", line 611, in getdoc
    return cleandoc(doc)
  File "/usr/local/lib/python3.7/inspect.py", line 629, in cleandoc
    margin = min(margin, indent)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 141
[2022-12-01T12:30:16.104+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:30:16.154+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 31.014 seconds
[2022-12-01T12:30:47.424+0000] {processor.py:154} INFO - Started process (PID=190) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:30:47.434+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T12:30:47.443+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:30:47.442+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:31:47.872+0000] {processor.py:154} INFO - Started process (PID=204) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:31:47.918+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T12:31:47.938+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:31:47.938+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:32:19.641+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:32:18.131+0000] {timeout.py:68} ERROR - Process timed out, PID: 204
[2022-12-01T12:32:20.668+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:32:19.744+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 20, in <module>
    from pandas.core.arrays.string_arrow import ArrowStringArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/string_arrow.py", line 65, in <module>
    import pyarrow.compute as pc
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 251, in <module>
    _make_global_functions()
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 248, in _make_global_functions
    g[cpp_name] = g[name] = _wrap_function(name, func)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 226, in _wrap_function
    option_class)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 207, in _make_signature
    options_sig = inspect.signature(option_class)
  File "/usr/local/lib/python3.7/inspect.py", line 3083, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/local/lib/python3.7/inspect.py", line 2833, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/usr/local/lib/python3.7/inspect.py", line 2328, in _signature_from_callable
    sigcls=sigcls)
  File "/usr/local/lib/python3.7/inspect.py", line 2281, in _signature_from_callable
    if isfunction(obj) or _signature_is_functionlike(obj):
  File "/usr/local/lib/python3.7/inspect.py", line 1849, in _signature_is_functionlike
    name = getattr(obj, '__name__', None)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 204
[2022-12-01T12:32:21.454+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:32:29.041+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 41.177 seconds
[2022-12-01T12:33:38.767+0000] {processor.py:154} INFO - Started process (PID=252) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:33:39.810+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T12:33:41.668+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:33:40.993+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:34:14.655+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:34:13.707+0000] {timeout.py:68} ERROR - Process timed out, PID: 252
[2022-12-01T12:34:15.347+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:34:14.863+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.base import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/base.py", line 60, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/missing.py", line 27, in <module>
    from pandas.compat._optional import import_optional_dependency
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 252
[2022-12-01T12:34:15.949+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:34:24.003+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 46.343 seconds
[2022-12-01T12:34:56.921+0000] {processor.py:154} INFO - Started process (PID=292) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:34:57.127+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T12:34:57.156+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:34:57.145+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:35:29.407+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:35:29.231+0000] {timeout.py:68} ERROR - Process timed out, PID: 292
[2022-12-01T12:35:31.556+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:35:30.080+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 292
[2022-12-01T12:35:39.044+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:36:46.866+0000] {processor.py:154} INFO - Started process (PID=325) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:36:48.201+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T12:36:49.468+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:36:49.062+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:37:31.142+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:37:26.338+0000] {timeout.py:68} ERROR - Process timed out, PID: 325
[2022-12-01T12:37:55.570+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:37:41.699+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "<frozen importlib._bootstrap>", line 978, in _find_and_load
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 325
[2022-12-01T12:38:35.415+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:43:59.524+0000] {processor.py:154} INFO - Started process (PID=438) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:44:00.945+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T12:44:05.053+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:44:04.442+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:44:39.420+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:44:39.070+0000] {timeout.py:68} ERROR - Process timed out, PID: 438
[2022-12-01T12:48:04.483+0000] {processor.py:154} INFO - Started process (PID=515) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:48:07.385+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T12:48:12.865+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:48:11.424+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T12:49:01.644+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:48:55.259+0000] {timeout.py:68} ERROR - Process timed out, PID: 515
[2022-12-01T13:16:35.368+0000] {processor.py:154} INFO - Started process (PID=42) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:16:35.372+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:16:35.374+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:16:35.374+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:16:52.960+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:16:52.924+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-p_l_rdre because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:17:27.876+0000] {processor.py:154} INFO - Started process (PID=79) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:17:27.901+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:17:27.914+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:17:27.913+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:17:37.572+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:17:37.572+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-iusvhh_o because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:17:37.932+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:17:37.932+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:17:38.467+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:17:38.593+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:17:38.592+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:17:38.628+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:17:38.628+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:17:38.658+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 10.958 seconds
[2022-12-01T13:18:10.581+0000] {processor.py:154} INFO - Started process (PID=105) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:18:10.591+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:18:10.605+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:18:10.601+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:18:32.900+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:18:32.900+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-snd7614_ because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:18:33.244+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:18:33.243+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:18:33.871+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:18:34.026+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:18:34.026+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:18:34.082+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:18:34.082+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:18:34.137+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 23.619 seconds
[2022-12-01T13:19:07.133+0000] {processor.py:154} INFO - Started process (PID=144) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:19:07.187+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:19:07.230+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:19:07.229+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:19:22.201+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:19:22.201+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-t4cw6oxm because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:19:22.731+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:19:22.730+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:19:23.266+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:19:23.353+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:19:23.352+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:19:23.400+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:19:23.399+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:19:23.422+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 16.753 seconds
[2022-12-01T13:19:54.545+0000] {processor.py:154} INFO - Started process (PID=180) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:19:54.553+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:19:54.560+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:19:54.560+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:20:07.178+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:20:07.165+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-apstryep because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:20:08.122+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:20:08.120+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:20:09.900+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:20:10.073+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:20:10.071+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:20:10.149+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:20:10.148+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:20:10.196+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 15.697 seconds
[2022-12-01T13:20:42.158+0000] {processor.py:154} INFO - Started process (PID=214) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:20:42.217+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:20:42.259+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:20:42.248+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:21:13.603+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:21:13.209+0000] {timeout.py:68} ERROR - Process timed out, PID: 214
[2022-12-01T13:21:13.892+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:21:13.638+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 20, in <module>
    from pandas.core.arrays.string_arrow import ArrowStringArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/string_arrow.py", line 65, in <module>
    import pyarrow.compute as pc
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 18, in <module>
    from pyarrow._compute import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 214
[2022-12-01T13:21:13.998+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:21:21.388+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 39.562 seconds
[2022-12-01T13:21:53.963+0000] {processor.py:154} INFO - Started process (PID=248) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:21:53.996+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:21:54.006+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:21:54.006+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:22:24.047+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:22:24.027+0000] {timeout.py:68} ERROR - Process timed out, PID: 248
[2022-12-01T13:22:24.094+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:22:24.054+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 4, in <module>
    from packages.ft_perceptron import *
  File "/opt/airflow/dags/packages/ft_perceptron.py", line 6, in <module>
    from matplotlib import pyplot as plt
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 49, in <module>
    import matplotlib.colorbar
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/colorbar.py", line 21, in <module>
    from matplotlib import _api, collections, cm, colors, contour, ticker
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/collections.py", line 20, in <module>
    from . import (_api, _path, artist, cbook, cm, colors as mcolors, docstring,
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 1766, in <module>
    Artist._update_set_signature_and_docstring()
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 148, in _update_set_signature_and_docstring
    + kwdoc(cls))
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 1762, in kwdoc
    'Properties:\n' + '\n'.join(ai.pprint_setters(leadingspace=4)))
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 1522, in pprint_setters
    for prop in sorted(self.get_setters()):
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 1449, in get_setters
    or self.is_alias(func)):
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/artist.py", line 1459, in is_alias
    return ds.startswith('Alias for ')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 248
[2022-12-01T13:22:24.114+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:22:24.634+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 30.794 seconds
[2022-12-01T13:22:57.840+0000] {processor.py:154} INFO - Started process (PID=281) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:22:57.987+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:22:58.246+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:22:58.067+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:23:29.236+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:23:28.585+0000] {timeout.py:68} ERROR - Process timed out, PID: 281
[2022-12-01T13:23:29.631+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:23:29.326+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 7, in <module>
    from pandas.core.arrays.categorical import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 113, in <module>
    from pandas.core.strings.object_array import ObjectStringArrayMixin
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/strings/__init__.py", line 31, in <module>
    from pandas.core.strings.base import BaseStringArrayMethods
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 281
[2022-12-01T13:23:29.820+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:23:38.126+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 40.750 seconds
[2022-12-01T13:24:11.867+0000] {processor.py:154} INFO - Started process (PID=320) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:24:11.962+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:24:11.975+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:24:11.975+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:24:42.456+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:24:42.123+0000] {timeout.py:68} ERROR - Process timed out, PID: 320
[2022-12-01T13:24:42.609+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:24:42.472+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 193, in <module>
    from pandas.core.series import Series
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 526, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 320
[2022-12-01T13:24:42.704+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:24:43.429+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 31.855 seconds
[2022-12-01T13:25:17.878+0000] {processor.py:154} INFO - Started process (PID=354) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:25:18.066+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:25:18.233+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:25:18.200+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:25:53.589+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:25:48.764+0000] {timeout.py:68} ERROR - Process timed out, PID: 354
[2022-12-01T13:25:55.618+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:25:54.464+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 122, in <module>
    from pandas.core.computation.api import eval
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/computation/api.py", line 3, in <module>
    from pandas.core.computation.eval import eval
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 354
[2022-12-01T13:25:55.732+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:25:57.985+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 40.100 seconds
[2022-12-01T13:26:31.950+0000] {processor.py:154} INFO - Started process (PID=387) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:26:32.015+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:26:32.027+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:26:32.027+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:27:26.515+0000] {processor.py:154} INFO - Started process (PID=421) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:27:26.541+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:27:26.550+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:27:26.550+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:28:17.889+0000] {processor.py:154} INFO - Started process (PID=443) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:28:17.904+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:28:17.920+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:28:17.919+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:28:48.335+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:28:48.011+0000] {timeout.py:68} ERROR - Process timed out, PID: 443
[2022-12-01T13:28:48.668+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:28:48.400+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 4, in <module>
    from packages.ft_perceptron import *
  File "/opt/airflow/dags/packages/ft_perceptron.py", line 2, in <module>
    from packages.source.net import NN, Linear, Relu
  File "/opt/airflow/dags/packages/source/net.py", line 4, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 38, in <module>
    from scipy.ndimage import measurements
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/ndimage/__init__.py", line 154, in <module>
    from .measurements import *
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 443
[2022-12-01T13:28:49.008+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:28:49.756+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 31.928 seconds
[2022-12-01T13:29:22.236+0000] {processor.py:154} INFO - Started process (PID=486) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:29:22.286+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:29:22.294+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:29:22.294+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:29:52.501+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:29:52.446+0000] {timeout.py:68} ERROR - Process timed out, PID: 486
[2022-12-01T13:29:52.746+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:29:52.539+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 4, in <module>
    from packages.ft_perceptron import *
  File "/opt/airflow/dags/packages/ft_perceptron.py", line 2, in <module>
    from packages.source.net import NN, Linear, Relu
  File "/opt/airflow/dags/packages/source/net.py", line 4, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 37, in <module>
    from scipy.spatial.distance import cdist
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/__init__.py", line 102, in <module>
    from ._geometric_slerp import geometric_slerp
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/_geometric_slerp.py", line 8, in <module>
    from scipy.spatial.distance import euclidean
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/distance.py", line 124, in <module>
    from ..special import rel_entr
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/special/__init__.py", line 646, in <module>
    from . import _basic
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/special/_basic.py", line 16, in <module>
    from . import orthogonal
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/special/orthogonal.py", line 122, in <module>
    class orthopoly1d(np.poly1d):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 486
[2022-12-01T13:29:52.789+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:29:53.205+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 31.269 seconds
[2022-12-01T13:30:24.441+0000] {processor.py:154} INFO - Started process (PID=522) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:30:24.446+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:30:24.447+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:30:24.447+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:30:29.896+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:30:29.895+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-4vuti9k2 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:30:31.672+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:30:31.652+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:31:07.398+0000] {processor.py:154} INFO - Started process (PID=548) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:31:07.595+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:31:07.621+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:31:07.621+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:31:37.669+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:31:37.665+0000] {timeout.py:68} ERROR - Process timed out, PID: 548
[2022-12-01T13:31:37.718+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:31:37.696+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 4, in <module>
    from packages.ft_perceptron import *
  File "/opt/airflow/dags/packages/ft_perceptron.py", line 2, in <module>
    from packages.source.net import NN, Linear, Relu
  File "/opt/airflow/dags/packages/source/net.py", line 4, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 448, in <module>
    from . import qmc
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 548
[2022-12-01T13:31:37.724+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:31:37.864+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 30.668 seconds
[2022-12-01T13:32:09.123+0000] {processor.py:154} INFO - Started process (PID=584) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:32:09.257+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:32:09.282+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:32:09.281+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:32:39.813+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:32:39.724+0000] {timeout.py:68} ERROR - Process timed out, PID: 584
[2022-12-01T13:32:39.893+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:32:39.823+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 4, in <module>
    from packages.ft_perceptron import *
  File "/opt/airflow/dags/packages/ft_perceptron.py", line 2, in <module>
    from packages.source.net import NN, Linear, Relu
  File "/opt/airflow/dags/packages/source/net.py", line 4, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/__init__.py", line 153, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
  File "_ccallback_c.pyx", line 212, in init scipy._lib._ccallback_c
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 73, in CFUNCTYPE
    def CFUNCTYPE(restype, *argtypes, **kw):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 584
[2022-12-01T13:32:39.928+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:32:40.293+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 31.004 seconds
[2022-12-01T13:33:17.148+0000] {processor.py:154} INFO - Started process (PID=630) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:33:17.157+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:33:17.177+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:33:17.177+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:34:11.289+0000] {processor.py:154} INFO - Started process (PID=653) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:34:11.299+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:34:11.301+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:11.301+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:34:26.244+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:26.237+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-0hvrpgtf because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:34:26.775+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:26.774+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:34:27.962+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:34:28.171+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:28.170+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:34:28.236+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:28.236+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:34:28.294+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 17.094 seconds
[2022-12-01T13:34:29.413+0000] {processor.py:154} INFO - Started process (PID=668) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:34:29.415+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:34:29.416+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:29.416+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:34:34.714+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:34.714+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-7nykab98 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:34:35.011+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:35.010+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:34:35.424+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:34:35.453+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:35.452+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:34:35.496+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:35.496+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:34:35.520+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 6.111 seconds
[2022-12-01T13:35:06.940+0000] {processor.py:154} INFO - Started process (PID=702) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:35:06.985+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:35:07.014+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:35:07.014+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:35:37.118+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:35:37.074+0000] {timeout.py:68} ERROR - Process timed out, PID: 702
[2022-12-01T13:35:37.237+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:35:37.125+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 4, in <module>
    from packages.ft_perceptron import *
  File "/opt/airflow/dags/packages/ft_perceptron.py", line 2, in <module>
    from packages.source.net import NN, Linear, Relu
  File "/opt/airflow/dags/packages/source/net.py", line 4, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 5087, in <module>
    MGCResult = namedtuple('MGCResult', ('stat', 'pvalue', 'mgc_dict'))
  File "/usr/local/lib/python3.7/collections/__init__.py", line 397, in namedtuple
    exec(s, namespace)
  File "<string>", line 1, in <module>
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 702
[2022-12-01T13:35:37.271+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:35:37.424+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 30.530 seconds
[2022-12-01T13:36:27.223+0000] {processor.py:154} INFO - Started process (PID=734) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:36:33.392+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:36:35.397+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:36:34.925+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:37:06.732+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:37:06.593+0000] {timeout.py:68} ERROR - Process timed out, PID: 734
[2022-12-01T13:37:07.519+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:37:06.971+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 589, in module_from_spec
  File "<frozen importlib._bootstrap>", line 553, in _init_module_attrs
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 734
[2022-12-01T13:37:07.705+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:37:52.536+0000] {processor.py:154} INFO - Started process (PID=765) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:37:52.728+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:37:52.990+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:37:52.985+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:38:23.450+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:38:23.410+0000] {timeout.py:68} ERROR - Process timed out, PID: 765
[2022-12-01T13:38:23.984+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:38:23.552+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 35, in init pandas._libs.tslibs.offsets
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1394, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 765
[2022-12-01T13:38:24.495+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:38:28.888+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 36.684 seconds
[2022-12-01T13:39:37.692+0000] {processor.py:154} INFO - Started process (PID=815) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:39:39.199+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:39:40.832+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:39:40.138+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:40:12.672+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:40:12.217+0000] {timeout.py:68} ERROR - Process timed out, PID: 815
[2022-12-01T13:40:18.471+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:40:13.613+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 815
[2022-12-01T13:40:19.645+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:40:57.083+0000] {processor.py:154} INFO - Started process (PID=848) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:40:57.772+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:40:59.322+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:40:59.165+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:41:33.020+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:41:32.672+0000] {timeout.py:68} ERROR - Process timed out, PID: 848
[2022-12-01T13:41:36.710+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:41:34.176+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timedeltas.pyx", line 61, in init pandas._libs.tslibs.timedeltas
  File "pandas/_libs/tslibs/fields.pyx", line 22, in init pandas._libs.tslibs.fields
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_config/__init__.py", line 28, in <module>
    from pandas._config.display import detect_console_encoding
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_config/display.py", line 61, in <module>
    "encoding", detect_console_encoding(), pc_encoding_doc, validator=cf.is_text
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_config/config.py", line 740, in inner
    return func(pkey, *args, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_config/config.py", line 473, in register_option
    if not re.match("^" + tokenize.Name + "$", k):
  File "/usr/local/lib/python3.7/re.py", line 175, in match
    return _compile(pattern, flags).match(string)
  File "/usr/local/lib/python3.7/re.py", line 278, in _compile
    return _cache[type(pattern), pattern, flags]
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 848
[2022-12-01T13:41:38.360+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:43:09.757+0000] {processor.py:154} INFO - Started process (PID=898) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:43:10.897+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:43:12.428+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:43:12.142+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:43:44.472+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:43:44.456+0000] {timeout.py:68} ERROR - Process timed out, PID: 898
[2022-12-01T13:43:46.045+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:43:44.718+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/intervaltree.pxi", line 7, in init pandas._libs.interval
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 898
[2022-12-01T13:43:47.021+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:44:45.534+0000] {processor.py:154} INFO - Started process (PID=933) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:44:46.022+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:44:46.155+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:44:46.154+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:45:34.224+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:45:33.900+0000] {timeout.py:68} ERROR - Process timed out, PID: 933
[2022-12-01T13:45:42.210+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:45:37.496+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "<frozen importlib._bootstrap>", line 978, in _find_and_load
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 933
[2022-12-01T13:45:49.906+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:46:34.330+0000] {processor.py:154} INFO - Started process (PID=940) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:46:35.569+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:46:37.531+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:46:36.574+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:50:20.266+0000] {processor.py:154} INFO - Started process (PID=42) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:50:20.274+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:50:20.277+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:50:20.277+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:50:25.113+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:50:25.101+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-si_sr8g5 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:50:25.624+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:50:25.622+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:50:27.051+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:50:27.549+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:50:27.546+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:50:27.652+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:50:27.651+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:50:27.781+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 7.526 seconds
[2022-12-01T13:50:58.143+0000] {processor.py:154} INFO - Started process (PID=70) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:50:58.145+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:50:58.148+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:50:58.148+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:51:02.630+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:02.629+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-fyzylod8 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:51:36.719+0000] {processor.py:154} INFO - Started process (PID=96) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:51:36.729+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:51:36.733+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:36.732+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:51:39.045+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:39.045+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-_u0iscg4 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:51:39.253+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:39.253+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:51:39.639+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:51:39.721+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:39.720+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:51:39.758+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:39.758+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T13:51:39.784+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 3.086 seconds
[2022-12-01T13:52:11.648+0000] {processor.py:154} INFO - Started process (PID=123) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T13:52:11.689+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T13:52:11.711+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:52:11.709+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:00:10.136+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:00:09.919+0000] {timeout.py:68} ERROR - Process timed out, PID: 123
[2022-12-01T14:00:10.753+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:00:10.475+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 30, in init pandas._libs.missing
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 123
[2022-12-01T14:00:10.873+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:01:13.382+0000] {processor.py:154} INFO - Started process (PID=152) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:01:13.608+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T14:01:13.805+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:01:13.805+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:01:45.758+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:01:45.568+0000] {timeout.py:68} ERROR - Process timed out, PID: 152
[2022-12-01T14:01:48.031+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:01:46.192+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 7, in <module>
    from pandas.core.util.hashing import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/util/hashing.py", line 17, in <module>
    from pandas._libs import lib
  File "pandas/_libs/lib.pyx", line 1, in init pandas._libs.lib
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 152
[2022-12-01T14:01:49.392+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:02:08.554+0000] {processor.py:154} INFO - Started process (PID=157) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:02:09.407+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T14:02:09.969+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:02:09.964+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:02:40.746+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:02:40.558+0000] {timeout.py:68} ERROR - Process timed out, PID: 157
[2022-12-01T14:02:42.562+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:02:41.172+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 157
[2022-12-01T14:02:43.473+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:03:04.881+0000] {processor.py:154} INFO - Started process (PID=159) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:03:06.010+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T14:03:06.326+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:03:06.324+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:03:37.225+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:03:36.830+0000] {timeout.py:68} ERROR - Process timed out, PID: 159
[2022-12-01T14:03:38.850+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:03:37.904+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timedeltas.pyx", line 61, in init pandas._libs.tslibs.timedeltas
  File "pandas/_libs/tslibs/fields.pyx", line 49, in init pandas._libs.tslibs.fields
  File "pandas/_libs/tslibs/strptime.pyx", line 633, in init pandas._libs.tslibs.strptime
  File "pandas/_libs/tslibs/strptime.pyx", line 538, in pandas._libs.tslibs.strptime.TimeRE.__init__
  File "pandas/_libs/tslibs/strptime.pyx", line 419, in pandas._libs.tslibs.strptime.LocaleTime.__init__
  File "pandas/_libs/tslibs/strptime.pyx", line 370, in pandas._libs.tslibs.strptime._getlang
  File "/usr/local/lib/python3.7/locale.py", line 575, in getlocale
    def getlocale(category=LC_CTYPE):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 159
[2022-12-01T14:03:40.025+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:03:47.812+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 45.011 seconds
[2022-12-01T14:04:42.581+0000] {processor.py:154} INFO - Started process (PID=162) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:04:42.970+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T14:04:43.381+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:04:43.254+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:05:14.041+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:05:14.004+0000] {timeout.py:68} ERROR - Process timed out, PID: 162
[2022-12-01T14:05:14.941+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:05:14.317+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 2449, in init pandas._libs.tslibs.offsets
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 162
[2022-12-01T14:05:15.386+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:05:18.461+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 36.711 seconds
[2022-12-01T14:06:20.969+0000] {processor.py:154} INFO - Started process (PID=167) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:06:21.071+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T14:06:21.382+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:06:21.377+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:06:54.684+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:06:51.885+0000] {timeout.py:68} ERROR - Process timed out, PID: 167
[2022-12-01T14:06:58.847+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:06:54.894+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 7, in <module>
    from pandas.core.arrays.categorical import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 99, in <module>
    from pandas.core.base import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/base.py", line 171, in <module>
    class SelectionMixin(Generic[FrameOrSeries]):
  File "/usr/local/lib/python3.7/typing.py", line 849, in __init_subclass__
    def __init_subclass__(cls, *args, **kwargs):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 167
[2022-12-01T14:07:00.246+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:07:08.311+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 47.413 seconds
[2022-12-01T14:07:32.531+0000] {processor.py:154} INFO - Started process (PID=193) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:07:32.586+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T14:07:32.673+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:07:32.672+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:08:05.613+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:08:05.582+0000] {timeout.py:68} ERROR - Process timed out, PID: 193
[2022-12-01T14:08:05.651+0000] {logging_mixin.py:137} WARNING - Exception ignored in: <module 'collections.abc' from '/usr/local/lib/python3.7/collections/abc.py'>
[2022-12-01T14:08:05.658+0000] {logging_mixin.py:137} WARNING - Traceback (most recent call last):
[2022-12-01T14:08:05.661+0000] {logging_mixin.py:137} WARNING -   File "<string>", line 1, in <module>
[2022-12-01T14:08:06.844+0000] {logging_mixin.py:137} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2022-12-01T14:08:07.047+0000] {logging_mixin.py:137} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2022-12-01T14:08:07.071+0000] {logging_mixin.py:137} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 193
[2022-12-01T14:08:09.270+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.7/importlib/_bootstrap.py:219 RuntimeWarning: Cython module failed to patch module with custom type
[2022-12-01T14:09:02.715+0000] {processor.py:154} INFO - Started process (PID=228) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:09:02.914+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T14:09:03.329+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:09:03.327+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:09:42.083+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:09:34.663+0000] {timeout.py:68} ERROR - Process timed out, PID: 228
[2022-12-01T14:09:44.586+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:09:42.140+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 7, in <module>
    from pandas.core.arrays.categorical import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 99, in <module>
    from pandas.core.base import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/base.py", line 171, in <module>
    class SelectionMixin(Generic[FrameOrSeries]):
  File "/usr/local/lib/python3.7/typing.py", line 849, in __init_subclass__
    def __init_subclass__(cls, *args, **kwargs):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 228
[2022-12-01T14:09:46.361+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:10:12.211+0000] {processor.py:154} INFO - Started process (PID=261) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:10:12.276+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T14:10:12.312+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:10:12.311+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T14:10:43.376+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:10:43.144+0000] {timeout.py:68} ERROR - Process timed out, PID: 261
[2022-12-01T14:10:52.470+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:10:43.875+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 6, in <module>
    import pyarrow as pa
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
  File "pyarrow/compat.pxi", line 49, in init pyarrow.lib
  File "/home/airflow/.local/lib/python3.7/site-packages/cloudpickle/__init__.py", line 1, in <module>
    from cloudpickle.cloudpickle import *  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 56, in <module>
    from .compat import pickle
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1364, in find_spec
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 261
[2022-12-01T14:10:53.627+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:52:53.257+0000] {processor.py:154} INFO - Started process (PID=41) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:52:53.262+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T16:52:53.265+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:52:53.264+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:52:57.129+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:52:57.129+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-enuvwhgu because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T16:52:57.709+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:52:57.708+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T16:52:58.588+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:52:58.965+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:52:58.964+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T16:52:59.071+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:52:59.070+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T16:52:59.143+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 5.905 seconds
[2022-12-01T16:53:30.360+0000] {processor.py:154} INFO - Started process (PID=78) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:53:30.362+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T16:53:30.364+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:53:30.364+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:53:31.635+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:53:31.635+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-nf3efasg because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T16:53:31.846+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:53:31.846+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T16:53:32.614+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:53:32.791+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:53:32.790+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T16:53:32.853+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:53:32.853+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-02T00:00:00+00:00
[2022-12-01T16:53:32.976+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 2.620 seconds
[2022-12-01T16:54:04.283+0000] {processor.py:154} INFO - Started process (PID=115) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:54:04.295+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T16:54:04.299+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:54:04.299+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:54:45.899+0000] {processor.py:154} INFO - Started process (PID=138) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:54:46.278+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T16:54:46.449+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:54:46.448+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:55:19.408+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:55:19.136+0000] {timeout.py:68} ERROR - Process timed out, PID: 138
[2022-12-01T16:55:19.747+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:55:19.456+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 108, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 14, in <module>
    from pandas._libs.indexing import NDFrameIndexerBase
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 138
[2022-12-01T16:55:19.795+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:56:15.506+0000] {processor.py:154} INFO - Started process (PID=177) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:56:15.806+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T16:56:15.846+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:56:15.846+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:56:47.615+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:56:46.324+0000] {timeout.py:68} ERROR - Process timed out, PID: 177
[2022-12-01T16:56:48.436+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:56:47.893+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 24, in <module>
    from pandas.core.algorithms import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/algorithms.py", line 75, in <module>
    from pandas.core.array_algos.take import take_nd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/array_algos/take.py", line 25, in <module>
    from pandas.core.construction import ensure_wrapped_if_datetimelike
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 177
[2022-12-01T16:56:48.803+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:57:08.976+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 53.856 seconds
[2022-12-01T16:57:12.232+0000] {processor.py:154} INFO - Started process (PID=207) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:57:12.289+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T16:57:12.312+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:57:12.306+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:57:42.485+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:57:42.399+0000] {timeout.py:68} ERROR - Process timed out, PID: 207
[2022-12-01T16:57:43.543+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:57:42.859+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timestamps.pyx", line 1, in init pandas._libs.tslibs.timestamps
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 207
[2022-12-01T16:57:44.794+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:57:54.326+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 43.186 seconds
[2022-12-01T16:58:35.096+0000] {processor.py:154} INFO - Started process (PID=229) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:58:35.245+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T16:58:35.355+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:58:35.355+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T16:59:07.459+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:59:06.871+0000] {timeout.py:68} ERROR - Process timed out, PID: 229
[2022-12-01T16:59:14.402+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:59:09.087+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/nattype.pyx", line 1, in init pandas._libs.tslibs.nattype
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 229
[2022-12-01T16:59:14.602+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:00:19.120+0000] {processor.py:154} INFO - Started process (PID=273) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:00:20.242+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T17:00:21.314+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:00:21.053+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:00:55.817+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:00:55.228+0000] {timeout.py:68} ERROR - Process timed out, PID: 273
[2022-12-01T17:02:23.589+0000] {processor.py:154} INFO - Started process (PID=317) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:02:27.080+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T17:02:29.918+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:02:28.952+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:03:21.106+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:03:14.043+0000] {timeout.py:68} ERROR - Process timed out, PID: 317
[2022-12-01T17:03:24.399+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:03:22.049+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 2, in <module>
    from airflow.operators.python import PythonOperator
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 317
[2022-12-01T17:03:26.531+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:05:00.767+0000] {processor.py:154} INFO - Started process (PID=344) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:05:03.220+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T17:05:06.456+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:05:06.199+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:05:44.807+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:05:43.211+0000] {timeout.py:68} ERROR - Process timed out, PID: 344
[2022-12-01T17:05:47.463+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:05:45.784+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 2, in <module>
    from airflow.operators.python import PythonOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 196, in <module>
    class BranchPythonOperator(PythonOperator, SkipMixin):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 435, in __new__
    new_cls.__init__ = cls._apply_defaults(new_cls.__init__)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 328, in _apply_defaults
    sig_cache = signature(func)
  File "/usr/local/lib/python3.7/inspect.py", line 3083, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/local/lib/python3.7/inspect.py", line 2833, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/usr/local/lib/python3.7/inspect.py", line 2284, in _signature_from_callable
    return _signature_from_function(sigcls, obj)
  File "/usr/local/lib/python3.7/inspect.py", line 2179, in _signature_from_function
    default=default))
  File "/usr/local/lib/python3.7/inspect.py", line 2467, in __init__
    def __init__(self, name, kind, *, default=_empty, annotation=_empty):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 344
[2022-12-01T17:05:51.048+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:09:31.118+0000] {processor.py:154} INFO - Started process (PID=444) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:09:31.591+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T17:09:33.235+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:09:33.109+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:10:24.987+0000] {processor.py:154} INFO - Started process (PID=483) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:10:26.332+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T17:10:26.796+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:10:26.724+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:11:02.601+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:11:00.677+0000] {timeout.py:68} ERROR - Process timed out, PID: 483
[2022-12-01T17:11:15.343+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:11:04.004+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 483
[2022-12-01T17:11:19.854+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:22:22.710+0000] {processor.py:154} INFO - Started process (PID=99) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:22:22.755+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T17:22:22.758+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:22:22.758+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:22:54.639+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:22:54.447+0000] {timeout.py:68} ERROR - Process timed out, PID: 99
[2022-12-01T17:22:55.444+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:22:54.839+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 4, in <module>
    from packages.ft_perceptron import *
  File "/opt/airflow/dags/packages/ft_perceptron.py", line 2, in <module>
    from packages.source.net import NN, Linear, Relu
  File "/opt/airflow/dags/packages/source/net.py", line 4, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 50, in <module>
    from ._hypotests import _all_partitions
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 99
[2022-12-01T17:22:55.882+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:22:58.555+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 35.834 seconds
[2022-12-01T17:23:33.495+0000] {processor.py:154} INFO - Started process (PID=141) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:23:33.518+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T17:23:33.558+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:23:33.553+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:27:39.430+0000] {processor.py:154} INFO - Started process (PID=208) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:27:39.729+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-12-01T17:27:39.933+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:27:39.908+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-12-01T17:28:13.711+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:28:12.884+0000] {timeout.py:68} ERROR - Process timed out, PID: 208
