[2022-12-01T11:05:25.558+0000] {processor.py:154} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:05:25.577+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T11:05:25.595+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:05:25.594+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:05:37.492+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:05:37.437+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ll8sm2c0 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T11:05:39.872+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:05:39.850+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T11:05:43.636+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:05:44.920+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:05:44.916+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T11:05:45.218+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:05:45.218+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T11:05:45.369+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 19.911 seconds
[2022-12-01T11:06:17.141+0000] {processor.py:154} INFO - Started process (PID=80) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:06:17.143+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T11:06:17.145+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:06:17.145+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:06:26.064+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:06:26.063+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-bhwhttfm because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T11:06:26.535+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:06:26.534+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T11:06:27.725+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:06:27.924+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:06:27.924+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T11:06:27.984+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:06:27.984+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T11:06:28.094+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 10.977 seconds
[2022-12-01T11:06:59.332+0000] {processor.py:154} INFO - Started process (PID=118) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:06:59.356+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T11:06:59.360+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:06:59.360+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:07:24.701+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:07:24.686+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-o3sdxorv because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T11:07:28.307+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:07:28.285+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T11:07:29.838+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:07:29.447+0000] {timeout.py:68} ERROR - Process timed out, PID: 118
[2022-12-01T11:07:30.680+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:07:30.007+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 5, in <module>
    from packages.ft_perceptron import *
  File "/opt/airflow/dags/packages/ft_perceptron.py", line 6, in <module>
    from matplotlib import pyplot as plt
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 49, in <module>
    import matplotlib.colorbar
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/colorbar.py", line 26, in <module>
    import matplotlib.spines as mspines
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 118
[2022-12-01T11:07:30.887+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:07:31.417+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 32.097 seconds
[2022-12-01T11:08:04.805+0000] {processor.py:154} INFO - Started process (PID=162) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:08:04.810+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T11:08:04.814+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:08:04.814+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:08:07.018+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:08:07.017+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-54l__f7n because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T11:08:07.195+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:08:07.195+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T11:08:07.610+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:08:07.693+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:08:07.692+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T11:08:07.729+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:08:07.729+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T11:08:07.756+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 2.964 seconds
[2022-12-01T11:08:38.528+0000] {processor.py:154} INFO - Started process (PID=187) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:08:38.541+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T11:08:38.568+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:08:38.568+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:09:10.895+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:09:10.671+0000] {timeout.py:68} ERROR - Process timed out, PID: 187
[2022-12-01T11:09:12.288+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:09:11.027+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 1219, in _path_importer_cache
KeyError: '/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/linalg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 1197, in _path_hooks
zipimport.ZipImportError: not a Zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 400, in <module>
    from .optimize import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 36, in <module>
    from ._numdiff import approx_derivative
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_numdiff.py", line 6, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/linalg/__init__.py", line 111, in <module>
    from .isolve import *
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1249, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1221, in _path_importer_cache
  File "<frozen importlib._bootstrap_external>", line 1197, in _path_hooks
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 187
[2022-12-01T11:09:13.251+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:09:15.816+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 36.513 seconds
[2022-12-01T11:09:56.051+0000] {processor.py:154} INFO - Started process (PID=212) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:09:56.361+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T11:09:56.642+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:09:56.603+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:10:27.259+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:10:26.935+0000] {timeout.py:68} ERROR - Process timed out, PID: 212
[2022-12-01T11:10:29.086+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:10:27.535+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/parallel.py", line 26, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 17, in <module>
    from .pool import MemmappingPool
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/pool.py", line 31, in <module>
    from ._memmapping_reducer import get_memmapping_reducers
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_memmapping_reducer.py", line 37, in <module>
    from .externals.loky.backend import resource_tracker
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/__init__.py", line 19, in <module>
    from .backend.reduction import set_loky_pickler
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/backend/reduction.py", line 82, in <module>
    from joblib.externals import cloudpickle  # noqa: F401
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/cloudpickle/__init__.py", line 1, in <module>
    from .cloudpickle import *  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 46, in <module>
    import opcode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 212
[2022-12-01T11:10:30.842+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:10:50.684+0000] {processor.py:154} INFO - Started process (PID=242) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:10:50.735+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T11:10:50.757+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:10:50.756+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:11:21.291+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:11:21.074+0000] {timeout.py:68} ERROR - Process timed out, PID: 242
[2022-12-01T11:11:22.722+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:11:21.573+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 400, in <module>
    from .optimize import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 36, in <module>
    from ._numdiff import approx_derivative
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_numdiff.py", line 8, in <module>
    from ._group_columns import group_dense, group_sparse
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 667, in _load_unlocked
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 242
[2022-12-01T11:11:23.095+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:11:28.189+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 37.854 seconds
[2022-12-01T11:12:07.442+0000] {processor.py:154} INFO - Started process (PID=279) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:12:07.717+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T11:12:07.967+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:12:07.922+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:12:39.001+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:12:38.579+0000] {timeout.py:68} ERROR - Process timed out, PID: 279
[2022-12-01T11:12:39.075+0000] {logging_mixin.py:137} WARNING - Exception ignored in: <function _get_module_lock.<locals>.cb at 0xffffa7b5da70>
[2022-12-01T11:12:39.086+0000] {logging_mixin.py:137} WARNING - Traceback (most recent call last):
[2022-12-01T11:12:39.130+0000] {logging_mixin.py:137} WARNING -   File "<frozen importlib._bootstrap>", line 176, in cb
[2022-12-01T11:12:39.247+0000] {logging_mixin.py:137} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2022-12-01T11:12:39.410+0000] {logging_mixin.py:137} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2022-12-01T11:12:39.598+0000] {logging_mixin.py:137} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 279
[2022-12-01T11:13:26.855+0000] {processor.py:154} INFO - Started process (PID=314) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:13:27.410+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T11:13:27.782+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:13:27.774+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:14:00.332+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:14:00.089+0000] {timeout.py:68} ERROR - Process timed out, PID: 314
[2022-12-01T11:14:01.661+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:14:00.629+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 37, in <module>
    from scipy.spatial.distance import cdist
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/__init__.py", line 101, in <module>
    from ._procrustes import procrustes
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/_procrustes.py", line 9, in <module>
    from scipy.linalg import orthogonal_procrustes
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/__init__.py", line 195, in <module>
    from .misc import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/misc.py", line 3, in <module>
    from .blas import get_blas_funcs
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/blas.py", line 213, in <module>
    from scipy.linalg import _fblas
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 314
[2022-12-01T11:14:03.536+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:15:03.477+0000] {processor.py:154} INFO - Started process (PID=364) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T11:15:03.545+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T11:15:03.574+0000] {logging_mixin.py:137} INFO - [2022-12-01T11:15:03.574+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:26:39.180+0000] {processor.py:154} INFO - Started process (PID=42) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:26:39.189+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T12:26:39.191+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:26:39.190+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:26:54.365+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:26:54.363+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-1no2nnpy because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T12:26:57.032+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:26:57.011+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T12:27:04.068+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:27:08.012+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:27:07.931+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T12:27:08.705+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:27:08.704+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T12:27:09.301+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 30.096 seconds
[2022-12-01T12:27:42.481+0000] {processor.py:154} INFO - Started process (PID=78) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:27:42.491+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T12:27:42.502+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:27:42.501+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:28:13.536+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:28:13.146+0000] {timeout.py:68} ERROR - Process timed out, PID: 78
[2022-12-01T12:28:23.661+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:28:14.200+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 422, in <module>
    from ._dual_annealing import dual_annealing
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 812, in get_code
  File "<frozen importlib._bootstrap_external>", line 953, in path_stats
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 78
[2022-12-01T12:28:25.007+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:28:26.472+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 44.237 seconds
[2022-12-01T12:28:59.597+0000] {processor.py:154} INFO - Started process (PID=121) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:28:59.601+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T12:28:59.610+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:28:59.610+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:29:50.292+0000] {processor.py:154} INFO - Started process (PID=151) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:29:50.339+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T12:29:50.456+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:29:50.455+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:30:14.253+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:30:14.248+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-aszgiden because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T12:30:15.158+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:30:15.158+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T12:30:16.504+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:30:16.775+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:30:16.773+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T12:30:16.831+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:30:16.830+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T12:30:16.865+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 26.843 seconds
[2022-12-01T12:30:47.429+0000] {processor.py:154} INFO - Started process (PID=189) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:30:47.435+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T12:30:47.444+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:30:47.442+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:31:47.210+0000] {processor.py:154} INFO - Started process (PID=203) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:31:47.341+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T12:31:47.511+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:31:47.494+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:32:18.157+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:32:17.955+0000] {timeout.py:68} ERROR - Process timed out, PID: 203
[2022-12-01T12:32:20.296+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:32:18.427+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 401, in <module>
    from ._minimize import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 25, in <module>
    from ._trustregion_krylov import _minimize_trust_krylov
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 203
[2022-12-01T12:32:21.694+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:32:27.971+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 42.192 seconds
[2022-12-01T12:33:12.467+0000] {processor.py:154} INFO - Started process (PID=234) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:33:12.936+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T12:33:13.071+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:33:13.070+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:33:46.071+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:33:45.694+0000] {timeout.py:68} ERROR - Process timed out, PID: 234
[2022-12-01T12:33:48.931+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:33:46.673+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/__init__.py", line 126, in <module>
    from scipy.__config__ import show as show_config
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1364, in find_spec
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 234
[2022-12-01T12:33:49.995+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:34:38.578+0000] {processor.py:154} INFO - Started process (PID=283) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:34:38.930+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T12:34:39.321+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:34:39.141+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:35:11.599+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:35:11.482+0000] {timeout.py:68} ERROR - Process timed out, PID: 283
[2022-12-01T12:35:13.801+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:35:11.816+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 23, in <module>
    from .murmurhash import murmurhash3_32
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 283
[2022-12-01T12:35:15.577+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:35:56.549+0000] {processor.py:154} INFO - Started process (PID=309) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:35:58.040+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T12:35:59.524+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:35:58.963+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:36:39.197+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:36:36.107+0000] {timeout.py:68} ERROR - Process timed out, PID: 309
[2022-12-01T12:36:42.897+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:36:40.237+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/__init__.py", line 82, in <module>
    if callable(_fun) and not isinstance(_fun, type):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 309
[2022-12-01T12:36:44.308+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:37:11.287+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 77.049 seconds
[2022-12-01T12:43:59.863+0000] {processor.py:154} INFO - Started process (PID=435) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:44:02.540+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T12:44:04.854+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:44:04.199+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:46:05.826+0000] {processor.py:154} INFO - Started process (PID=494) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:46:06.871+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T12:46:13.459+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:46:12.213+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T12:47:02.338+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:47:01.259+0000] {timeout.py:68} ERROR - Process timed out, PID: 494
[2022-12-01T12:47:41.342+0000] {logging_mixin.py:137} INFO - [2022-12-01T12:47:33.716+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 2, in <module>
    from airflow.operators.python import PythonOperator
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 494
[2022-12-01T12:47:46.280+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:16:35.356+0000] {processor.py:154} INFO - Started process (PID=41) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:16:35.372+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:16:35.380+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:16:35.380+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:16:52.957+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:16:52.931+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-s8vhlx5j because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:16:57.992+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:16:57.985+0000] {font_manager.py:1061} WARNING - Matplotlib is building the font cache; this may take a moment.
[2022-12-01T13:17:29.843+0000] {processor.py:154} INFO - Started process (PID=81) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:17:29.864+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:17:29.869+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:17:29.869+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:17:37.555+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:17:37.555+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-wxquma7i because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:17:37.922+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:17:37.921+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:17:38.467+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:17:38.591+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:17:38.591+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:17:38.628+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:17:38.628+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T13:17:38.657+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 8.861 seconds
[2022-12-01T13:18:10.572+0000] {processor.py:154} INFO - Started process (PID=104) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:18:10.584+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:18:10.594+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:18:10.590+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:18:32.876+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:18:32.876+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-dd0g1qk0 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:18:33.251+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:18:33.250+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:18:33.945+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:18:34.003+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:18:34.003+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:18:34.045+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:18:34.045+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T13:18:34.070+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 23.575 seconds
[2022-12-01T13:19:07.121+0000] {processor.py:154} INFO - Started process (PID=143) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:19:07.176+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:19:07.232+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:19:07.230+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:19:22.236+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:19:22.235+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-yb9n7j_v because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:19:22.733+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:19:22.733+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:19:23.275+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:19:23.352+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:19:23.351+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:19:23.388+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:19:23.388+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T13:19:23.415+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 16.647 seconds
[2022-12-01T13:19:54.545+0000] {processor.py:154} INFO - Started process (PID=179) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:19:54.553+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:19:54.559+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:19:54.559+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:20:07.396+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:20:07.385+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-p9hozjog because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:20:08.132+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:20:08.131+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:20:09.895+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:20:10.073+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:20:10.071+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:20:10.156+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:20:10.156+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T13:20:10.222+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 15.723 seconds
[2022-12-01T13:20:42.144+0000] {processor.py:154} INFO - Started process (PID=213) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:20:42.213+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:20:42.242+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:20:42.241+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:21:12.590+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:21:12.560+0000] {timeout.py:68} ERROR - Process timed out, PID: 213
[2022-12-01T13:21:13.025+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:21:12.606+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 401, in <module>
    from ._minimize import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 33, in <module>
    from .slsqp import _minimize_slsqp
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/slsqp.py", line 20, in <module>
    from scipy.optimize._slsqp import slsqp
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 213
[2022-12-01T13:21:13.295+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:21:19.116+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 37.320 seconds
[2022-12-01T13:21:51.648+0000] {processor.py:154} INFO - Started process (PID=247) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:21:51.657+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:21:51.664+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:21:51.662+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:22:21.717+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:22:21.701+0000] {timeout.py:68} ERROR - Process timed out, PID: 247
[2022-12-01T13:22:21.759+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:22:21.730+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 143, in <module>
    from pandas.io.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/api.py", line 39, in <module>
    from pandas.io.stata import read_stata
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 247
[2022-12-01T13:22:21.770+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:22:22.080+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 30.498 seconds
[2022-12-01T13:22:55.575+0000] {processor.py:154} INFO - Started process (PID=280) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:22:55.711+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:22:55.801+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:22:55.798+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:23:27.805+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:23:27.632+0000] {timeout.py:68} ERROR - Process timed out, PID: 280
[2022-12-01T13:23:28.428+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:23:27.859+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 37, in <module>
    from scipy.spatial.distance import cdist
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/__init__.py", line 102, in <module>
    from ._geometric_slerp import geometric_slerp
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/_geometric_slerp.py", line 8, in <module>
    from scipy.spatial.distance import euclidean
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/distance.py", line 124, in <module>
    from ..special import rel_entr
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/special/__init__.py", line 646, in <module>
    from . import _basic
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/special/_basic.py", line 17, in <module>
    from ._comb import _comb_int
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 280
[2022-12-01T13:23:28.661+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:23:29.965+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 34.469 seconds
[2022-12-01T13:24:07.827+0000] {processor.py:154} INFO - Started process (PID=318) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:24:07.909+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:24:07.945+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:24:07.945+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:24:38.198+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:24:38.156+0000] {timeout.py:68} ERROR - Process timed out, PID: 318
[2022-12-01T13:24:38.625+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:24:38.244+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 413, in <module>
    from ._linprog import linprog, linprog_verbose_callback
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_linprog.py", line 22, in <module>
    from ._linprog_highs import _linprog_highs
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_linprog_highs.py", line 20, in <module>
    from ._highs._highs_wrapper import _highs_wrapper
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 318
[2022-12-01T13:24:39.002+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:24:39.678+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 32.099 seconds
[2022-12-01T13:25:12.723+0000] {processor.py:154} INFO - Started process (PID=353) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:25:12.785+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:25:12.856+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:25:12.839+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:25:43.041+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:25:42.939+0000] {timeout.py:68} ERROR - Process timed out, PID: 353
[2022-12-01T13:25:44.100+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:25:43.125+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/model_selection/__init__.py", line 23, in <module>
    from ._validation import cross_val_score
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 31, in <module>
    from ..metrics import check_scoring
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/metrics/__init__.py", line 39, in <module>
    from ._dist_metrics import DistanceMetric
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 353
[2022-12-01T13:25:44.594+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:26:26.225+0000] {processor.py:154} INFO - Started process (PID=384) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:26:26.247+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:26:26.267+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:26:26.266+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:27:10.871+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:27:10.867+0000] {timeout.py:68} ERROR - Process timed out, PID: 384
[2022-12-01T13:27:10.886+0000] {logging_mixin.py:137} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0xffffb77e7e60>
[2022-12-01T13:27:10.888+0000] {logging_mixin.py:137} WARNING - Traceback (most recent call last):
[2022-12-01T13:27:10.889+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/weakref.py", line 358, in remove
[2022-12-01T13:27:10.891+0000] {logging_mixin.py:137} WARNING -     def remove(k, selfref=ref(self)):
[2022-12-01T13:27:10.892+0000] {logging_mixin.py:137} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2022-12-01T13:27:10.893+0000] {logging_mixin.py:137} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2022-12-01T13:27:10.893+0000] {logging_mixin.py:137} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 384
[2022-12-01T13:27:11.684+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:27:11.683+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-kx0nisxc because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:27:12.075+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:27:12.073+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:27:12.472+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:27:12.582+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:27:12.581+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:27:12.605+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:27:12.604+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T13:27:12.623+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 46.478 seconds
[2022-12-01T13:27:48.403+0000] {processor.py:154} INFO - Started process (PID=433) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:27:48.424+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:27:48.458+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:27:48.449+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:28:21.549+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:28:21.436+0000] {timeout.py:68} ERROR - Process timed out, PID: 433
[2022-12-01T13:28:22.059+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:28:21.570+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 401, in <module>
    from ._minimize import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 25, in <module>
    from ._trustregion_krylov import _minimize_trust_krylov
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_trustregion_krylov.py", line 2, in <module>
    from ._trlib import (get_trlib_quadratic_subproblem)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_trlib/__init__.py", line 1, in <module>
    from ._trlib import TRLIBQuadraticSubproblem
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 433
[2022-12-01T13:28:22.240+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:28:24.540+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 36.227 seconds
[2022-12-01T13:28:56.732+0000] {processor.py:154} INFO - Started process (PID=467) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:28:56.737+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:28:56.739+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:28:56.739+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:29:01.057+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:29:01.056+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-kak1ub01 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:29:01.285+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:29:01.284+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:29:01.635+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:29:01.703+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:29:01.703+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:29:01.722+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:29:01.722+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T13:29:01.740+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 5.024 seconds
[2022-12-01T13:29:54.418+0000] {processor.py:154} INFO - Started process (PID=501) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:29:54.428+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:29:54.444+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:29:54.444+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:30:16.574+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:30:16.548+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-dg3es690 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:30:18.003+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:30:17.997+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:30:19.734+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:30:19.842+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:30:19.841+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:30:19.931+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:30:19.931+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T13:30:19.989+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 25.679 seconds
[2022-12-01T13:30:52.543+0000] {processor.py:154} INFO - Started process (PID=542) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:30:52.568+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:30:52.600+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:30:52.599+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:31:27.168+0000] {processor.py:154} INFO - Started process (PID=559) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:31:27.183+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:31:27.192+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:31:27.192+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:31:38.363+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:31:38.362+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-axrfq308 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:31:38.559+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:31:38.558+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:31:38.912+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:31:38.970+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:31:38.970+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:31:38.999+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:31:38.999+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T13:31:39.014+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 11.983 seconds
[2022-12-01T13:32:31.138+0000] {processor.py:154} INFO - Started process (PID=601) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:32:31.239+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:32:31.261+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:32:31.260+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:32:50.055+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:32:50.050+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ty_8nhk1 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:32:51.264+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:32:51.258+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:32:52.352+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:32:52.503+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:32:52.502+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:32:52.587+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:32:52.586+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T13:32:52.664+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 21.639 seconds
[2022-12-01T13:33:17.121+0000] {processor.py:154} INFO - Started process (PID=629) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:33:17.151+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:33:17.174+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:33:17.173+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:34:01.154+0000] {processor.py:154} INFO - Started process (PID=652) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:34:01.199+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:34:01.274+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:01.274+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:34:29.408+0000] {processor.py:154} INFO - Started process (PID=667) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:34:29.410+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:34:29.412+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:29.411+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:34:34.497+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:34.497+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-3x4ksk2v because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:34:34.806+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:34.805+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:34:35.277+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:34:35.328+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:35.327+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:34:35.379+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:34:35.379+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T13:34:35.428+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 6.025 seconds
[2022-12-01T13:35:06.950+0000] {processor.py:154} INFO - Started process (PID=701) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:35:06.986+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:35:07.008+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:35:07.007+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:35:37.074+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:35:37.050+0000] {timeout.py:68} ERROR - Process timed out, PID: 701
[2022-12-01T13:35:37.143+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:35:37.096+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 143, in <module>
    from pandas.io.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/api.py", line 8, in <module>
    from pandas.io.excel import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/__init__.py", line 1, in <module>
    from pandas.io.excel._base import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 61, in <module>
    from pandas.io.parsers import TextParser
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/__init__.py", line 1, in <module>
    from pandas.io.parsers.readers import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 45, in <module>
    from pandas.io.parsers.base_parser import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 701
[2022-12-01T13:35:37.155+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:35:37.378+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 30.580 seconds
[2022-12-01T13:36:23.470+0000] {processor.py:154} INFO - Started process (PID=733) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:36:25.668+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:36:33.331+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:36:29.703+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:37:05.144+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:37:05.121+0000] {timeout.py:68} ERROR - Process timed out, PID: 733
[2022-12-01T13:37:06.269+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:37:05.548+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 37, in <module>
    from scipy.spatial.distance import cdist
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/__init__.py", line 101, in <module>
    from ._procrustes import procrustes
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/_procrustes.py", line 9, in <module>
    from scipy.linalg import orthogonal_procrustes
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/__init__.py", line 195, in <module>
    from .misc import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/misc.py", line 3, in <module>
    from .blas import get_blas_funcs
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/blas.py", line 213, in <module>
    from scipy.linalg import _fblas
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 733
[2022-12-01T13:37:15.037+0000] {processor.py:154} INFO - Started process (PID=753) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:37:16.682+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:37:20.451+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:37:17.117+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:37:51.227+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:37:51.054+0000] {timeout.py:68} ERROR - Process timed out, PID: 753
[2022-12-01T13:37:51.731+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:37:51.330+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 37, in <module>
    from scipy.spatial.distance import cdist
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/__init__.py", line 101, in <module>
    from ._procrustes import procrustes
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/_procrustes.py", line 9, in <module>
    from scipy.linalg import orthogonal_procrustes
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/__init__.py", line 212, in <module>
    from ._decomp_update import *
  File "_decomp_update.pyx", line 1, in init scipy.linalg._decomp_update
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 753
[2022-12-01T13:37:52.086+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:38:10.400+0000] {processor.py:154} INFO - Started process (PID=773) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:38:11.563+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:38:12.802+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:38:12.698+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:38:43.377+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:38:43.081+0000] {timeout.py:68} ERROR - Process timed out, PID: 773
[2022-12-01T13:38:44.421+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:38:43.642+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 38, in <module>
    from scipy.ndimage import measurements
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/ndimage/__init__.py", line 154, in <module>
    from .measurements import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/ndimage/measurements.py", line 36, in <module>
    from . import morphology
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 773
[2022-12-01T13:38:45.112+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:38:49.409+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 43.262 seconds
[2022-12-01T13:38:58.636+0000] {processor.py:154} INFO - Started process (PID=804) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:38:58.851+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:38:59.098+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:38:59.097+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:39:30.237+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:39:30.072+0000] {timeout.py:68} ERROR - Process timed out, PID: 804
[2022-12-01T13:39:35.981+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:39:30.267+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 240, in <module>
    from . import csgraph
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/csgraph/__init__.py", line 196, in <module>
    from ._reordering import reverse_cuthill_mckee, structural_rank
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 804
[2022-12-01T13:39:37.200+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:39:45.880+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 48.167 seconds
[2022-12-01T13:39:59.900+0000] {processor.py:154} INFO - Started process (PID=823) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:40:00.354+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:40:05.695+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:40:04.286+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:40:37.430+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:40:37.348+0000] {timeout.py:68} ERROR - Process timed out, PID: 823
[2022-12-01T13:40:38.718+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:40:37.615+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 230, in <module>
    from .lil import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/lil.py", line 17, in <module>
    from . import _csparsetools
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1045, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _verbose_message
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 823
[2022-12-01T13:40:39.590+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:41:22.955+0000] {processor.py:154} INFO - Started process (PID=861) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:41:23.009+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:41:23.043+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:41:23.036+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:41:53.920+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:41:53.283+0000] {timeout.py:68} ERROR - Process timed out, PID: 861
[2022-12-01T13:41:56.725+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:41:54.260+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 228, in <module>
    from .csr import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/csr.py", line 14, in <module>
    from .compressed import _cs_matrix
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1394, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 861
[2022-12-01T13:42:09.281+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:42:45.177+0000] {processor.py:154} INFO - Started process (PID=887) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:42:46.480+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:42:50.081+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:42:49.958+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:44:18.046+0000] {processor.py:154} INFO - Started process (PID=923) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:44:18.649+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:44:19.510+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:44:19.322+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:44:51.470+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:44:51.330+0000] {timeout.py:68} ERROR - Process timed out, PID: 923
[2022-12-01T13:45:06.463+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:44:52.277+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 240, in <module>
    from . import csgraph
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/csgraph/__init__.py", line 192, in <module>
    from ._flow import maximum_flow
  File "_flow.pyx", line 3, in init scipy.sparse.csgraph._flow
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 923
[2022-12-01T13:45:08.078+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:45:45.471+0000] {processor.py:154} INFO - Started process (PID=934) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:45:48.144+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:45:50.334+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:45:49.824+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:50:20.244+0000] {processor.py:154} INFO - Started process (PID=41) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:50:20.252+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:50:20.254+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:50:20.254+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:50:25.094+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:50:25.092+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-l8w7pp_i because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:50:25.623+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:50:25.622+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:50:27.049+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:50:27.565+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:50:27.565+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:50:27.662+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:50:27.662+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T13:50:27.804+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 7.570 seconds
[2022-12-01T13:50:58.142+0000] {processor.py:154} INFO - Started process (PID=69) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:50:58.145+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:50:58.148+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:50:58.148+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:51:02.632+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:02.631+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-2kof_69k because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:51:05.542+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:05.499+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:51:39.653+0000] {processor.py:154} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:51:39.655+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:51:39.657+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:39.657+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:51:40.820+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:40.819+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-sbqx3j6v because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T13:51:40.998+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:40.998+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T13:51:41.398+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:51:41.538+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:41.537+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T13:51:41.592+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:51:41.591+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T13:51:41.704+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 2.055 seconds
[2022-12-01T13:52:13.938+0000] {processor.py:154} INFO - Started process (PID=124) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T13:52:13.958+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T13:52:13.961+0000] {logging_mixin.py:137} INFO - [2022-12-01T13:52:13.960+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:00:11.500+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:00:11.493+0000] {timeout.py:68} ERROR - Process timed out, PID: 124
[2022-12-01T14:00:11.810+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:00:11.610+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/parallel.py", line 26, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 17, in <module>
    from .pool import MemmappingPool
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/pool.py", line 31, in <module>
    from ._memmapping_reducer import get_memmapping_reducers
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_memmapping_reducer.py", line 37, in <module>
    from .externals.loky.backend import resource_tracker
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/__init__.py", line 19, in <module>
    from .backend.reduction import set_loky_pickler
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/backend/reduction.py", line 82, in <module>
    from joblib.externals import cloudpickle  # noqa: F401
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/cloudpickle/__init__.py", line 1, in <module>
    from .cloudpickle import *  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 56, in <module>
    from .compat import pickle
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1364, in find_spec
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 124
[2022-12-01T14:00:12.150+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:00:13.286+0000] {processor.py:154} INFO - Started process (PID=140) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:00:13.305+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T14:00:13.310+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:00:13.310+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:00:43.370+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:00:43.225+0000] {timeout.py:68} ERROR - Process timed out, PID: 140
[2022-12-01T14:00:44.178+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:00:43.438+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/__init__.py", line 113, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/memory.py", line 28, in <module>
    from .func_inspect import get_func_code, get_func_name, filter_args
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 140
[2022-12-01T14:00:45.145+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:01:14.304+0000] {processor.py:154} INFO - Started process (PID=153) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:01:14.321+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T14:01:14.326+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:01:14.324+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:01:46.154+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:01:45.712+0000] {timeout.py:68} ERROR - Process timed out, PID: 153
[2022-12-01T14:01:47.602+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:01:46.255+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 240, in <module>
    from . import csgraph
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/csgraph/__init__.py", line 196, in <module>
    from ._reordering import reverse_cuthill_mckee, structural_rank
  File "_reordering.pyx", line 7, in init scipy.sparse.csgraph._reordering
  File "<frozen importlib._bootstrap>", line 1009, in _handle_fromlist
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 153
[2022-12-01T14:01:49.633+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:02:56.962+0000] {processor.py:154} INFO - Started process (PID=158) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:02:57.219+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T14:02:57.370+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:02:57.368+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:03:28.137+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:03:27.953+0000] {timeout.py:68} ERROR - Process timed out, PID: 158
[2022-12-01T14:03:34.710+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:03:28.286+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/__init__.py", line 113, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/memory.py", line 28, in <module>
    from .func_inspect import get_func_code, get_func_name, filter_args
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/func_inspect.py", line 22, in <module>
    full_argspec_type = collections.namedtuple('FullArgSpec', full_argspec_fields)
  File "/usr/local/lib/python3.7/collections/__init__.py", line 464, in namedtuple
    class_namespace[name] = property(itemgetter_object, doc=doc)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 158
[2022-12-01T14:03:38.542+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:04:00.951+0000] {processor.py:154} INFO - Started process (PID=161) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:04:01.060+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T14:04:01.104+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:04:01.103+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:04:33.179+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:04:32.460+0000] {timeout.py:68} ERROR - Process timed out, PID: 161
[2022-12-01T14:04:35.659+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:04:34.169+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/__init__.py", line 113, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/memory.py", line 28, in <module>
    from .func_inspect import get_func_code, get_func_name, filter_args
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/func_inspect.py", line 18, in <module>
    from .logger import pformat
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 161
[2022-12-01T14:04:39.031+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:05:25.121+0000] {processor.py:154} INFO - Started process (PID=165) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:05:25.386+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T14:05:25.649+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:05:25.617+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:05:56.460+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:05:56.423+0000] {timeout.py:68} ERROR - Process timed out, PID: 165
[2022-12-01T14:05:59.376+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:05:56.666+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 1219, in _path_importer_cache
KeyError: '/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/csgraph'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 240, in <module>
    from . import csgraph
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/csgraph/__init__.py", line 182, in <module>
    from ._laplacian import laplacian
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1249, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1221, in _path_importer_cache
  File "<frozen importlib._bootstrap_external>", line 1197, in _path_hooks
  File "<frozen importlib._bootstrap_external>", line 1447, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 102, in _path_isdir
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 165
[2022-12-01T14:06:02.217+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:06:38.910+0000] {processor.py:154} INFO - Started process (PID=168) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:06:39.117+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T14:06:39.259+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:06:39.258+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:07:15.088+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:07:14.969+0000] {timeout.py:68} ERROR - Process timed out, PID: 168
[2022-12-01T14:07:17.431+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:07:15.115+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/parallel.py", line 26, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 17, in <module>
    from .pool import MemmappingPool
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/pool.py", line 31, in <module>
    from ._memmapping_reducer import get_memmapping_reducers
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_memmapping_reducer.py", line 37, in <module>
    from .externals.loky.backend import resource_tracker
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/__init__.py", line 18, in <module>
    from .backend.context import cpu_count
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/backend/__init__.py", line 2, in <module>
    from multiprocessing import synchronize
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 168
[2022-12-01T14:07:18.620+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:08:12.363+0000] {processor.py:154} INFO - Started process (PID=201) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:08:12.514+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T14:08:12.641+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:08:12.638+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:08:44.655+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:08:44.637+0000] {timeout.py:68} ERROR - Process timed out, PID: 201
[2022-12-01T14:08:45.609+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:08:44.683+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 230, in <module>
    from .lil import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/lil.py", line 17, in <module>
    from . import _csparsetools
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 201
[2022-12-01T14:08:47.339+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:08:52.338+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 41.586 seconds
[2022-12-01T14:10:01.747+0000] {processor.py:154} INFO - Started process (PID=260) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:10:02.033+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T14:10:02.595+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:10:02.455+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:10:33.669+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:10:33.473+0000] {timeout.py:68} ERROR - Process timed out, PID: 260
[2022-12-01T14:10:35.359+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:10:33.975+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/parallel.py", line 26, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 260
[2022-12-01T14:10:38.869+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:11:13.711+0000] {processor.py:154} INFO - Started process (PID=291) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T14:11:13.948+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T14:11:14.397+0000] {logging_mixin.py:137} INFO - [2022-12-01T14:11:14.351+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:52:53.229+0000] {processor.py:154} INFO - Started process (PID=40) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:52:53.234+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T16:52:53.240+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:52:53.240+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:52:57.134+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:52:57.133+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-rp2dgc9b because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T16:52:57.707+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:52:57.706+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T16:52:58.605+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:52:59.057+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:52:59.057+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T16:52:59.102+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:52:59.102+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T16:52:59.188+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 5.966 seconds
[2022-12-01T16:53:30.360+0000] {processor.py:154} INFO - Started process (PID=77) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:53:30.362+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T16:53:30.364+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:53:30.364+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:53:31.717+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:53:31.717+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-dh5kb36s because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-12-01T16:53:31.887+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:53:31.886+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-12-01T16:53:32.610+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:53:32.726+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:53:32.724+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-01T16:53:32.791+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:53:32.791+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-12-01T16:53:32.856+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 2.501 seconds
[2022-12-01T16:54:04.283+0000] {processor.py:154} INFO - Started process (PID=114) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:54:04.292+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T16:54:04.299+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:54:04.299+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:54:45.983+0000] {processor.py:154} INFO - Started process (PID=137) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:54:46.374+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T16:54:46.470+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:54:46.464+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:55:35.666+0000] {processor.py:154} INFO - Started process (PID=160) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:55:35.971+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T16:55:36.250+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:55:36.170+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:56:10.015+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:56:09.993+0000] {timeout.py:68} ERROR - Process timed out, PID: 160
[2022-12-01T16:56:10.347+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:56:10.049+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 37, in <module>
    from scipy.spatial.distance import cdist
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/__init__.py", line 101, in <module>
    from ._procrustes import procrustes
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/_procrustes.py", line 9, in <module>
    from scipy.linalg import orthogonal_procrustes
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/__init__.py", line 195, in <module>
    from .misc import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/misc.py", line 3, in <module>
    from .blas import get_blas_funcs
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/blas.py", line 213, in <module>
    from scipy.linalg import _fblas
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 160
[2022-12-01T16:56:10.469+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:56:13.703+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 38.927 seconds
[2022-12-01T16:56:48.054+0000] {processor.py:154} INFO - Started process (PID=191) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:56:48.178+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T16:56:48.241+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:56:48.241+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:57:18.916+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:57:18.792+0000] {timeout.py:68} ERROR - Process timed out, PID: 191
[2022-12-01T16:57:20.199+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:57:19.404+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 240, in <module>
    from . import csgraph
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/csgraph/__init__.py", line 193, in <module>
    from ._matching import (
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 191
[2022-12-01T16:57:20.526+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:57:23.239+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 35.956 seconds
[2022-12-01T16:58:07.122+0000] {processor.py:154} INFO - Started process (PID=226) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:58:07.677+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T16:58:08.211+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:58:08.066+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:58:39.077+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:58:38.874+0000] {timeout.py:68} ERROR - Process timed out, PID: 226
[2022-12-01T16:58:44.518+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:58:39.348+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 228, in <module>
    from .csr import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/csr.py", line 14, in <module>
    from .compressed import _cs_matrix
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 17, in <module>
    from ._index import IndexMixin
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 226
[2022-12-01T16:58:44.747+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:59:38.655+0000] {processor.py:154} INFO - Started process (PID=257) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T16:59:39.714+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T16:59:40.438+0000] {logging_mixin.py:137} INFO - [2022-12-01T16:59:40.233+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:00:13.981+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:00:13.482+0000] {timeout.py:68} ERROR - Process timed out, PID: 257
[2022-12-01T17:00:14.854+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:00:14.248+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/__init__.py", line 83, in <module>
    _fun = _deprecated(_msg.format(_key))(_fun)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/_lib/deprecation.py", line 16, in wrap
    @functools.wraps(fun)
  File "/usr/local/lib/python3.7/functools.py", line 60, in update_wrapper
    getattr(wrapper, attr).update(getattr(wrapped, attr, {}))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 257
[2022-12-01T17:00:16.294+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:01:33.285+0000] {processor.py:154} INFO - Started process (PID=302) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:01:45.235+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T17:01:51.737+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:01:50.422+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:04:38.400+0000] {processor.py:154} INFO - Started process (PID=342) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:04:42.353+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T17:04:46.903+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:04:46.273+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:05:32.618+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:05:29.926+0000] {timeout.py:68} ERROR - Process timed out, PID: 342
[2022-12-01T17:05:45.358+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:05:32.746+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1368, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1408, in _fill_cache
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 342
[2022-12-01T17:05:47.969+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:08:21.076+0000] {processor.py:154} INFO - Started process (PID=425) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:08:21.927+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T17:08:23.271+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:08:23.057+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:09:06.856+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:09:00.611+0000] {timeout.py:68} ERROR - Process timed out, PID: 425
[2022-12-01T17:09:26.185+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:09:08.420+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 81, in <module>
    from . import __check_build  # noqa: F401
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__check_build/__init__.py", line 48, in <module>
    from ._check_build import check_build  # noqa
  File "<frozen importlib._bootstrap>", line 978, in _find_and_load
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 425
[2022-12-01T17:09:30.272+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:10:27.925+0000] {processor.py:154} INFO - Started process (PID=481) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:10:31.234+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T17:10:36.131+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:10:35.773+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:11:16.433+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:11:15.379+0000] {timeout.py:68} ERROR - Process timed out, PID: 481
[2022-12-01T17:11:18.275+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:11:17.508+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 53, in <module>
    os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "True")
  File "/usr/local/lib/python3.7/os.py", line 718, in setdefault
    self[key] = value
  File "/usr/local/lib/python3.7/os.py", line 687, in __setitem__
    self.putenv(key, value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 481
[2022-12-01T17:11:21.081+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:22:22.663+0000] {processor.py:154} INFO - Started process (PID=98) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:22:22.688+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T17:22:22.692+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:22:22.692+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:22:57.659+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:22:57.516+0000] {timeout.py:68} ERROR - Process timed out, PID: 98
[2022-12-01T17:22:58.042+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:22:57.769+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 876, in <module>
    class DataFrameGroupBy(GroupBy[DataFrame]):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 965, in DataFrameGroupBy
    def aggregate(self, func=None, *args, engine=None, engine_kwargs=None, **kwargs):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 98
[2022-12-01T17:22:58.249+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:22:58.774+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 36.155 seconds
[2022-12-01T17:23:33.078+0000] {processor.py:154} INFO - Started process (PID=140) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:23:33.127+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T17:23:33.203+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:23:33.202+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:24:03.709+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:24:03.359+0000] {timeout.py:68} ERROR - Process timed out, PID: 140
[2022-12-01T17:24:04.523+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:24:03.935+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 64, in <module>
    from pandas.core.aggregation import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 140
[2022-12-01T17:24:04.563+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:24:08.078+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 35.348 seconds
[2022-12-01T17:26:51.203+0000] {processor.py:154} INFO - Started process (PID=189) to work on /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:26:51.386+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-12-01T17:26:51.495+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:26:51.494+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-12-01T17:27:22.661+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:27:22.341+0000] {timeout.py:68} ERROR - Process timed out, PID: 189
[2022-12-01T17:27:27.047+0000] {logging_mixin.py:137} INFO - [2022-12-01T17:27:22.862+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 37, in <module>
    from scipy.spatial.distance import cdist
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/__init__.py", line 96, in <module>
    from .kdtree import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/kdtree.py", line 5, in <module>
    from .ckdtree import cKDTree, cKDTreeNode
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 189
[2022-12-01T17:27:31.869+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
